<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('karyawan')->insert([
            ['id_karyawan' => 'K001', 'name' => 'Admin', 'username' => 'admin', 'email' => 'admin@gmail.com', 'password' => Hash::make('password'), 'jabatan' => 'admin', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_karyawan' => 'K002', 'name' => 'Budi Mekanik', 'username' => 'budi', 'email' => 'budi@gmail.com', 'password' => Hash::make('password'), 'jabatan' => 'mekanik', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]
        ]);

        DB::table('pelanggan')->insert([
            ['id_pelanggan' => 'P001', 'nama_pelanggan' => 'Dannarnd', 'nomor_hp' => '081234564546', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_pelanggan' => 'P002', 'nama_pelanggan' => 'Andi', 'nomor_hp' => '0853472893', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]
        ]);

        DB::table('kendaraan')->insert([
            ['id_kendaraan' => 'M001', 'id_pelanggan' => 'P001', 'nomor_polisi' => 'BL1234AD', 'merk_mobil' => 'Toyota Avanza', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_kendaraan' => 'M002', 'id_pelanggan' => 'P002', 'nomor_polisi' => 'BK1234CD', 'merk_mobil' => 'Honda Jazz', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]
        ]);

        DB::table('sparepart')->insert([
            ['kode_barang' => 'RUT001', 'nama_barang' => 'Upper Tank Avanza Lama', 'harga' => 290000, 'stok' => 23, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT002', 'nama_barang' => 'Upper Tank Avanza VVT-i', 'harga' => 170000, 'stok' => 12, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT003', 'nama_barang' => 'Upper Tank Avanza Dual VVT-i', 'harga' => 320000, 'stok' => 4, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT004', 'nama_barang' => 'Upper Tank All New Avanza', 'harga' => 420000, 'stok' => 19, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT005', 'nama_barang' => 'Upper Tank Innova Bensin 2.0', 'harga' => 170000, 'stok' => 10, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT006', 'nama_barang' => 'Upper Tank Innova Diesel 2.5', 'harga' => 330000, 'stok' => 1, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT007', 'nama_barang' => 'Upper Tank Innova Reborn Bensin', 'harga' => 290000, 'stok' => 17, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT008', 'nama_barang' => 'Upper Tank Innova Reborn Diesel', 'harga' => 430000, 'stok' => 8, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT009', 'nama_barang' => 'Upper Tank Innova Zenix', 'harga' => 440000, 'stok' => 16, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT010', 'nama_barang' => 'Upper Tank Fortuner Non-VNT', 'harga' => 190000, 'stok' => 3, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT011', 'nama_barang' => 'Upper Tank Fortuner VNT', 'harga' => 440000, 'stok' => 2, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT012', 'nama_barang' => 'Upper Tank Fortuner VRZ', 'harga' => 170000, 'stok' => 8, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT013', 'nama_barang' => 'Upper Tank Hilux Single Cabin', 'harga' => 270000, 'stok' => 16, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT014', 'nama_barang' => 'Upper Tank Hilux Double Cabin', 'harga' => 150000, 'stok' => 9, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT015', 'nama_barang' => 'Upper Tank Agya 1.0', 'harga' => 440000, 'stok' => 10, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT016', 'nama_barang' => 'Upper Tank Agya 1.2', 'harga' => 160000, 'stok' => 19, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT017', 'nama_barang' => 'Upper Tank Calya 1.2', 'harga' => 390000, 'stok' => 9, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT018', 'nama_barang' => 'Upper Tank Rush Lama', 'harga' => 230000, 'stok' => 10, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT019', 'nama_barang' => 'Upper Tank All New Rush', 'harga' => 220000, 'stok' => 13, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT020', 'nama_barang' => 'Upper Tank Raize 1.0 Turbo', 'harga' => 190000, 'stok' => 8, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT021', 'nama_barang' => 'Upper Tank Raize 1.2', 'harga' => 340000, 'stok' => 11, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT022', 'nama_barang' => 'Upper Tank Yaris Bakpao', 'harga' => 340000, 'stok' => 12, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT023', 'nama_barang' => 'Upper Tank Yaris Lele', 'harga' => 170000, 'stok' => 14, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT024', 'nama_barang' => 'Upper Tank Yaris Joker', 'harga' => 450000, 'stok' => 4, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT025', 'nama_barang' => 'Upper Tank Vios Gen 1', 'harga' => 400000, 'stok' => 14, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT026', 'nama_barang' => 'Upper Tank Vios Gen 2', 'harga' => 210000, 'stok' => 4, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT027', 'nama_barang' => 'Upper Tank Vios Gen 3', 'harga' => 260000, 'stok' => 18, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT028', 'nama_barang' => 'Upper Tank Camry 2.4', 'harga' => 170000, 'stok' => 21, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT029', 'nama_barang' => 'Upper Tank Camry 2.5', 'harga' => 280000, 'stok' => 2, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT030', 'nama_barang' => 'Upper Tank Altis Gen 1', 'harga' => 250000, 'stok' => 4, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT031', 'nama_barang' => 'Upper Tank Altis Gen 2', 'harga' => 190000, 'stok' => 13, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT032', 'nama_barang' => 'Upper Tank Alphard 2.4', 'harga' => 450000, 'stok' => 5, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT033', 'nama_barang' => 'Upper Tank Alphard 2.5', 'harga' => 380000, 'stok' => 7, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT034', 'nama_barang' => 'Upper Tank Vellfire', 'harga' => 240000, 'stok' => 12, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT035', 'nama_barang' => 'Upper Tank Sienta', 'harga' => 430000, 'stok' => 16, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT036', 'nama_barang' => 'Upper Tank Voxy', 'harga' => 200000, 'stok' => 4, 'batas_minimum' => 3],
            ['kode_barang' => 'RCT001', 'nama_barang' => 'Core Radiator Avanza Manual 1ply', 'harga' => 600000, 'stok' => 5, 'batas_minimum' => 2],
            ['kode_barang' => 'RCT002', 'nama_barang' => 'Core Radiator Innova Bensin Manual', 'harga' => 850000, 'stok' => 3, 'batas_minimum' => 1],
            ['kode_barang' => 'RCM001', 'nama_barang' => 'Core Radiator L300 Diesel Kuningan', 'harga' => 1200000, 'stok' => 4, 'batas_minimum' => 2],
            ['kode_barang' => 'RCO001', 'nama_barang' => 'Core Radiator Panther Kuningan', 'harga' => 1100000, 'stok' => 3, 'batas_minimum' => 3],
            ['kode_barang' => 'RCN001', 'nama_barang' => 'Core Radiator Grand Livina Matic', 'harga' => 750000, 'stok' => 2, 'batas_minimum' => 2],
            ['kode_barang' => 'RCS001', 'nama_barang' => 'Core Radiator Futura / Carry', 'harga' => 550000, 'stok' => 6, 'batas_minimum' => 6],
            ['kode_barang' => 'RUT037', 'nama_barang' => 'Upper Tank Nav1', 'harga' => 250000, 'stok' => 8, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT038', 'nama_barang' => 'Upper Tank Harrier 2.4', 'harga' => 160000, 'stok' => 9, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT039', 'nama_barang' => 'Upper Tank Kijang Super', 'harga' => 220000, 'stok' => 12, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT040', 'nama_barang' => 'Upper Tank Kijang Grand Extra', 'harga' => 370000, 'stok' => 11, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT041', 'nama_barang' => 'Upper Tank Kijang Kapsul 1.8', 'harga' => 150000, 'stok' => 9, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT042', 'nama_barang' => 'Upper Tank Kijang Kapsul 2.0', 'harga' => 200000, 'stok' => 10, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT043', 'nama_barang' => 'Upper Tank Kijang Kapsul Diesel', 'harga' => 380000, 'stok' => 16, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT044', 'nama_barang' => 'Upper Tank Hiace Commuter', 'harga' => 410000, 'stok' => 21, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT045', 'nama_barang' => 'Upper Tank Hiace Premio', 'harga' => 230000, 'stok' => 20, 'batas_minimum' => 3],
            ['kode_barang' => 'RUT046', 'nama_barang' => 'Upper Tank Land Cruiser VX80', 'harga' => 240000, 'stok' => 19, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH001', 'nama_barang' => 'Upper Tank Jazz GD3', 'harga' => 290000, 'stok' => 12, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH002', 'nama_barang' => 'Upper Tank Jazz GE8', 'harga' => 270000, 'stok' => 17, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH003', 'nama_barang' => 'Upper Tank Jazz GK5', 'harga' => 180000, 'stok' => 17, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH004', 'nama_barang' => 'Upper Tank Brio 1.2', 'harga' => 360000, 'stok' => 8, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH005', 'nama_barang' => 'Upper Tank Mobilio', 'harga' => 420000, 'stok' => 16, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH006', 'nama_barang' => 'Upper Tank BRV Lama', 'harga' => 150000, 'stok' => 14, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH007', 'nama_barang' => 'Upper Tank All New BRV', 'harga' => 160000, 'stok' => 7, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH008', 'nama_barang' => 'Upper Tank HRV 1.5', 'harga' => 440000, 'stok' => 15, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH009', 'nama_barang' => 'Upper Tank HRV 1.8', 'harga' => 160000, 'stok' => 16, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH010', 'nama_barang' => 'Upper Tank HRV Turbo', 'harga' => 320000, 'stok' => 6, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH011', 'nama_barang' => 'Upper Tank CRV Gen 1', 'harga' => 360000, 'stok' => 14, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH012', 'nama_barang' => 'Upper Tank CRV Gen 2', 'harga' => 360000, 'stok' => 2, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH013', 'nama_barang' => 'Upper Tank CRV Gen 3 2.0', 'harga' => 370000, 'stok' => 13, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH014', 'nama_barang' => 'Upper Tank CRV Gen 3 2.4', 'harga' => 290000, 'stok' => 3, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH015', 'nama_barang' => 'Upper Tank CRV Gen 4', 'harga' => 390000, 'stok' => 19, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH016', 'nama_barang' => 'Upper Tank CRV Gen 5 Turbo', 'harga' => 190000, 'stok' => 8, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH017', 'nama_barang' => 'Upper Tank Civic Ferio', 'harga' => 420000, 'stok' => 7, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH018', 'nama_barang' => 'Upper Tank Civic FD1', 'harga' => 210000, 'stok' => 5, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH019', 'nama_barang' => 'Upper Tank Civic FD2', 'harga' => 410000, 'stok' => 3, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH020', 'nama_barang' => 'Upper Tank Civic FB', 'harga' => 260000, 'stok' => 19, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH021', 'nama_barang' => 'Upper Tank Civic Turbo FC', 'harga' => 200000, 'stok' => 20, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH022', 'nama_barang' => 'Upper Tank City GD8', 'harga' => 290000, 'stok' => 13, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH023', 'nama_barang' => 'Upper Tank City GM2', 'harga' => 360000, 'stok' => 10, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH024', 'nama_barang' => 'Upper Tank City GM6', 'harga' => 380000, 'stok' => 14, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH025', 'nama_barang' => 'Upper Tank Accord CP2', 'harga' => 220000, 'stok' => 14, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH026', 'nama_barang' => 'Upper Tank Accord CR2', 'harga' => 440000, 'stok' => 3, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH027', 'nama_barang' => 'Upper Tank Freed', 'harga' => 440000, 'stok' => 5, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH028', 'nama_barang' => 'Upper Tank Odyssey RB1', 'harga' => 360000, 'stok' => 11, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH029', 'nama_barang' => 'Upper Tank Odyssey RC1', 'harga' => 390000, 'stok' => 9, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH030', 'nama_barang' => 'Upper Tank Stream 1.7', 'harga' => 190000, 'stok' => 11, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH031', 'nama_barang' => 'Upper Tank Stream 2.0', 'harga' => 350000, 'stok' => 16, 'batas_minimum' => 3],
            ['kode_barang' => 'RUH032', 'nama_barang' => 'Upper Tank Elyson', 'harga' => 310000, 'stok' => 5, 'batas_minimum' => 3],
            ['kode_barang' => 'RUD001', 'nama_barang' => 'Upper Tank Xenia 1.0', 'harga' => 380000, 'stok' => 18, 'batas_minimum' => 3],
            ['kode_barang' => 'RUD002', 'nama_barang' => 'Upper Tank Xenia 1.3', 'harga' => 310000, 'stok' => 4, 'batas_minimum' => 3],
            ['kode_barang' => 'RUD003', 'nama_barang' => 'Upper Tank All New Xenia', 'harga' => 200000, 'stok' => 21, 'batas_minimum' => 3],
            ['kode_barang' => 'RUD004', 'nama_barang' => 'Upper Tank Terios Lama', 'harga' => 320000, 'stok' => 18, 'batas_minimum' => 3],
            ['kode_barang' => 'RUD005', 'nama_barang' => 'Upper Tank All New Terios', 'harga' => 210000, 'stok' => 18, 'batas_minimum' => 3],
            ['kode_barang' => 'RUD006', 'nama_barang' => 'Upper Tank Gran Max 1.3', 'harga' => 260000, 'stok' => 9, 'batas_minimum' => 3],
            ['kode_barang' => 'RUD007', 'nama_barang' => 'Upper Tank Gran Max 1.5', 'harga' => 210000, 'stok' => 19, 'batas_minimum' => 3],
            ['kode_barang' => 'RUD008', 'nama_barang' => 'Upper Tank Luxio', 'harga' => 340000, 'stok' => 19, 'batas_minimum' => 3],
            ['kode_barang' => 'RUD009', 'nama_barang' => 'Upper Tank Ayla 1.0', 'harga' => 260000, 'stok' => 14, 'batas_minimum' => 3],
            ['kode_barang' => 'RUD010', 'nama_barang' => 'Upper Tank Ayla 1.2', 'harga' => 370000, 'stok' => 18, 'batas_minimum' => 3],
            ['kode_barang' => 'RUD011', 'nama_barang' => 'Upper Tank Sigra 1.0', 'harga' => 450000, 'stok' => 4, 'batas_minimum' => 3],
            ['kode_barang' => 'RUD012', 'nama_barang' => 'Upper Tank Sigra 1.2', 'harga' => 300000, 'stok' => 14, 'batas_minimum' => 3],
            ['kode_barang' => 'RUD013', 'nama_barang' => 'Upper Tank Sirion Lama', 'harga' => 310000, 'stok' => 17, 'batas_minimum' => 3],
            ['kode_barang' => 'RUD014', 'nama_barang' => 'Upper Tank All New Sirion', 'harga' => 320000, 'stok' => 7, 'batas_minimum' => 3],
            ['kode_barang' => 'RUD015', 'nama_barang' => 'Upper Tank Taruna Karburator', 'harga' => 240000, 'stok' => 11, 'batas_minimum' => 3],
            ['kode_barang' => 'RUD016', 'nama_barang' => 'Upper Tank Taruna EFI', 'harga' => 440000, 'stok' => 3, 'batas_minimum' => 3],
            ['kode_barang' => 'RUD017', 'nama_barang' => 'Upper Tank Feroza', 'harga' => 380000, 'stok' => 19, 'batas_minimum' => 3],
            ['kode_barang' => 'RUD018', 'nama_barang' => 'Upper Tank Taft GT', 'harga' => 150000, 'stok' => 12, 'batas_minimum' => 3],
            ['kode_barang' => 'RUD019', 'nama_barang' => 'Upper Tank Taft Independent', 'harga' => 250000, 'stok' => 17, 'batas_minimum' => 3],
            ['kode_barang' => 'RUD020', 'nama_barang' => 'Upper Tank Rocky Lama', 'harga' => 210000, 'stok' => 8, 'batas_minimum' => 3],
            ['kode_barang' => 'RUD021', 'nama_barang' => 'Upper Tank Rocky Baru 1.0', 'harga' => 180000, 'stok' => 17, 'batas_minimum' => 3],
            ['kode_barang' => 'RUD022', 'nama_barang' => 'Upper Tank Rocky Baru 1.2', 'harga' => 260000, 'stok' => 17, 'batas_minimum' => 3],
            ['kode_barang' => 'RUD023', 'nama_barang' => 'Upper Tank Zebra 1.3', 'harga' => 320000, 'stok' => 21, 'batas_minimum' => 3],
            ['kode_barang' => 'RUS001', 'nama_barang' => 'Upper Tank Carry 1.0', 'harga' => 390000, 'stok' => 4, 'batas_minimum' => 3],
            ['kode_barang' => 'RUS002', 'nama_barang' => 'Upper Tank Carry Futura 1.5', 'harga' => 190000, 'stok' => 10, 'batas_minimum' => 3],
            ['kode_barang' => 'RUS003', 'nama_barang' => 'Upper Tank New Carry (Tayu)', 'harga' => 230000, 'stok' => 11, 'batas_minimum' => 3],
            ['kode_barang' => 'RUS004', 'nama_barang' => 'Upper Tank APV', 'harga' => 250000, 'stok' => 10, 'batas_minimum' => 3],
            ['kode_barang' => 'RUS005', 'nama_barang' => 'Upper Tank APV Arena', 'harga' => 430000, 'stok' => 21, 'batas_minimum' => 3],
            ['kode_barang' => 'RUS006', 'nama_barang' => 'Upper Tank Ertiga Lama', 'harga' => 340000, 'stok' => 19, 'batas_minimum' => 3],
            ['kode_barang' => 'RUS007', 'nama_barang' => 'Upper Tank All New Ertiga', 'harga' => 370000, 'stok' => 12, 'batas_minimum' => 3],
            ['kode_barang' => 'RUS008', 'nama_barang' => 'Upper Tank XL7', 'harga' => 170000, 'stok' => 4, 'batas_minimum' => 3],
            ['kode_barang' => 'RUS009', 'nama_barang' => 'Upper Tank SX4 X-Over', 'harga' => 160000, 'stok' => 13, 'batas_minimum' => 3],
            ['kode_barang' => 'RUS010', 'nama_barang' => 'Upper Tank SX4 S-Cross', 'harga' => 180000, 'stok' => 14, 'batas_minimum' => 3],
            ['kode_barang' => 'RUS011', 'nama_barang' => 'Upper Tank Grand Vitara 2.0', 'harga' => 170000, 'stok' => 14, 'batas_minimum' => 3],
            ['kode_barang' => 'RUS012', 'nama_barang' => 'Upper Tank Grand Vitara 2.4', 'harga' => 200000, 'stok' => 9, 'batas_minimum' => 3],
            ['kode_barang' => 'RUS013', 'nama_barang' => 'Upper Tank Ignis', 'harga' => 300000, 'stok' => 2, 'batas_minimum' => 3],
            ['kode_barang' => 'RUS014', 'nama_barang' => 'Upper Tank Baleno Lama', 'harga' => 250000, 'stok' => 14, 'batas_minimum' => 3],
            ['kode_barang' => 'RUS015', 'nama_barang' => 'Upper Tank Baleno Hatchback', 'harga' => 250000, 'stok' => 18, 'batas_minimum' => 3],
            ['kode_barang' => 'RUS016', 'nama_barang' => 'Upper Tank Aerio', 'harga' => 380000, 'stok' => 3, 'batas_minimum' => 3],
            ['kode_barang' => 'RUS017', 'nama_barang' => 'Upper Tank Swift ST', 'harga' => 410000, 'stok' => 18, 'batas_minimum' => 3],
            ['kode_barang' => 'RUS018', 'nama_barang' => 'Upper Tank Swift GT3', 'harga' => 270000, 'stok' => 10, 'batas_minimum' => 3],
            ['kode_barang' => 'RUS019', 'nama_barang' => 'Upper Tank Splash', 'harga' => 260000, 'stok' => 15, 'batas_minimum' => 3],
            ['kode_barang' => 'RUS020', 'nama_barang' => 'Upper Tank Jimny Katana', 'harga' => 210000, 'stok' => 14, 'batas_minimum' => 3],
            ['kode_barang' => 'RUS021', 'nama_barang' => 'Upper Tank Jimny JB74', 'harga' => 210000, 'stok' => 6, 'batas_minimum' => 3],
            ['kode_barang' => 'RUS022', 'nama_barang' => 'Upper Tank Karimun Kotak', 'harga' => 340000, 'stok' => 6, 'batas_minimum' => 3],
            ['kode_barang' => 'RUS023', 'nama_barang' => 'Upper Tank Karimun Wagon R', 'harga' => 300000, 'stok' => 5, 'batas_minimum' => 3],
            ['kode_barang' => 'RUM001', 'nama_barang' => 'Upper Tank Xpander', 'harga' => 390000, 'stok' => 5, 'batas_minimum' => 3],
            ['kode_barang' => 'RUM002', 'nama_barang' => 'Upper Tank Xpander Cross', 'harga' => 420000, 'stok' => 15, 'batas_minimum' => 3],
            ['kode_barang' => 'RUM003', 'nama_barang' => 'Upper Tank L300 Bensin', 'harga' => 300000, 'stok' => 14, 'batas_minimum' => 3],
            ['kode_barang' => 'RUM004', 'nama_barang' => 'Upper Tank L300 Diesel', 'harga' => 400000, 'stok' => 13, 'batas_minimum' => 3],
            ['kode_barang' => 'RUM005', 'nama_barang' => 'Upper Tank Pajero Sport Lama', 'harga' => 240000, 'stok' => 5, 'batas_minimum' => 3],
            ['kode_barang' => 'RUM006', 'nama_barang' => 'Upper Tank Pajero Sport Dakar', 'harga' => 280000, 'stok' => 15, 'batas_minimum' => 3],
            ['kode_barang' => 'RUM007', 'nama_barang' => 'Upper Tank All New Pajero Sport', 'harga' => 190000, 'stok' => 13, 'batas_minimum' => 3],
            ['kode_barang' => 'RUM008', 'nama_barang' => 'Upper Tank Outlander Sport', 'harga' => 280000, 'stok' => 7, 'batas_minimum' => 3],
            ['kode_barang' => 'RUM009', 'nama_barang' => 'Upper Tank Triton GLS', 'harga' => 370000, 'stok' => 6, 'batas_minimum' => 3],
            ['kode_barang' => 'RUM010', 'nama_barang' => 'Upper Tank Triton HDX', 'harga' => 280000, 'stok' => 19, 'batas_minimum' => 3],
            ['kode_barang' => 'RUM011', 'nama_barang' => 'Upper Tank Mirage', 'harga' => 160000, 'stok' => 7, 'batas_minimum' => 3],
            ['kode_barang' => 'RUM012', 'nama_barang' => 'Upper Tank Kuda Bensin 1.6', 'harga' => 320000, 'stok' => 5, 'batas_minimum' => 3],
            ['kode_barang' => 'RUM013', 'nama_barang' => 'Upper Tank Kuda Diesel 2.5', 'harga' => 290000, 'stok' => 2, 'batas_minimum' => 3],
            ['kode_barang' => 'RUM014', 'nama_barang' => 'Upper Tank Kuda Grandia 2.0', 'harga' => 230000, 'stok' => 3, 'batas_minimum' => 3],
            ['kode_barang' => 'RUM015', 'nama_barang' => 'Upper Tank Lancer DanGan', 'harga' => 250000, 'stok' => 9, 'batas_minimum' => 3],
            ['kode_barang' => 'RUM016', 'nama_barang' => 'Upper Tank Lancer Evo 3', 'harga' => 440000, 'stok' => 21, 'batas_minimum' => 3],
            ['kode_barang' => 'RUM017', 'nama_barang' => 'Upper Tank Lancer Evo 4', 'harga' => 210000, 'stok' => 17, 'batas_minimum' => 3],
            ['kode_barang' => 'RUM018', 'nama_barang' => 'Upper Tank Galant Hiu', 'harga' => 190000, 'stok' => 15, 'batas_minimum' => 3],
            ['kode_barang' => 'RUM019', 'nama_barang' => 'Upper Tank Colt Diesel Canter', 'harga' => 440000, 'stok' => 15, 'batas_minimum' => 3],
            ['kode_barang' => 'RUN001', 'nama_barang' => 'Upper Tank Grand Livina 1.5', 'harga' => 430000, 'stok' => 15, 'batas_minimum' => 3],
            ['kode_barang' => 'RUN002', 'nama_barang' => 'Upper Tank Grand Livina 1.8', 'harga' => 380000, 'stok' => 6, 'batas_minimum' => 3],
            ['kode_barang' => 'RUN003', 'nama_barang' => 'Upper Tank All New Livina', 'harga' => 350000, 'stok' => 20, 'batas_minimum' => 3],
            ['kode_barang' => 'RUN004', 'nama_barang' => 'Upper Tank March 1.2', 'harga' => 370000, 'stok' => 7, 'batas_minimum' => 3],
            ['kode_barang' => 'RUN005', 'nama_barang' => 'Upper Tank March 1.5', 'harga' => 330000, 'stok' => 6, 'batas_minimum' => 3],
            ['kode_barang' => 'RUN006', 'nama_barang' => 'Upper Tank Datsun Go', 'harga' => 190000, 'stok' => 5, 'batas_minimum' => 3],
            ['kode_barang' => 'RUN007', 'nama_barang' => 'Upper Tank Datsun Go+', 'harga' => 200000, 'stok' => 9, 'batas_minimum' => 3],
            ['kode_barang' => 'RUN008', 'nama_barang' => 'Upper Tank X-Trail T30', 'harga' => 300000, 'stok' => 15, 'batas_minimum' => 3],
            ['kode_barang' => 'RUN009', 'nama_barang' => 'Upper Tank X-Trail T31', 'harga' => 430000, 'stok' => 15, 'batas_minimum' => 3],
            ['kode_barang' => 'RUN010', 'nama_barang' => 'Upper Tank X-Trail T32', 'harga' => 350000, 'stok' => 9, 'batas_minimum' => 3],
            ['kode_barang' => 'RUN011', 'nama_barang' => 'Upper Tank Serena C24', 'harga' => 320000, 'stok' => 2, 'batas_minimum' => 3],
            ['kode_barang' => 'RUN012', 'nama_barang' => 'Upper Tank Serena C26', 'harga' => 320000, 'stok' => 10, 'batas_minimum' => 3],
            ['kode_barang' => 'RUN013', 'nama_barang' => 'Upper Tank Evalia', 'harga' => 190000, 'stok' => 8, 'batas_minimum' => 3],
            ['kode_barang' => 'RUN014', 'nama_barang' => 'Upper Tank Juke', 'harga' => 220000, 'stok' => 15, 'batas_minimum' => 3],
            ['kode_barang' => 'RUN015', 'nama_barang' => 'Upper Tank Navara D40', 'harga' => 210000, 'stok' => 12, 'batas_minimum' => 3],
            ['kode_barang' => 'RUN016', 'nama_barang' => 'Upper Tank Navara NP300', 'harga' => 420000, 'stok' => 10, 'batas_minimum' => 3],
            ['kode_barang' => 'RUN017', 'nama_barang' => 'Upper Tank Terrano', 'harga' => 220000, 'stok' => 15, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO001', 'nama_barang' => 'Upper Tank Isuzu Panther 2.3', 'harga' => 330000, 'stok' => 5, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO002', 'nama_barang' => 'Upper Tank Isuzu Panther 2.5', 'harga' => 190000, 'stok' => 10, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO003', 'nama_barang' => 'Upper Tank Isuzu Elf NKR', 'harga' => 180000, 'stok' => 12, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO004', 'nama_barang' => 'Upper Tank Isuzu MU-X', 'harga' => 290000, 'stok' => 14, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO005', 'nama_barang' => 'Upper Tank Wuling Confero', 'harga' => 320000, 'stok' => 6, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO006', 'nama_barang' => 'Upper Tank Wuling Cortez', 'harga' => 440000, 'stok' => 13, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO007', 'nama_barang' => 'Upper Tank Wuling Almaz', 'harga' => 160000, 'stok' => 4, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO008', 'nama_barang' => 'Upper Tank Wuling Formo', 'harga' => 420000, 'stok' => 11, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO009', 'nama_barang' => 'Upper Tank Ford Fiesta 1.4', 'harga' => 230000, 'stok' => 10, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO010', 'nama_barang' => 'Upper Tank Ford Fiesta 1.5', 'harga' => 320000, 'stok' => 3, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO011', 'nama_barang' => 'Upper Tank Ford Everest', 'harga' => 440000, 'stok' => 2, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO012', 'nama_barang' => 'Upper Tank Ford Ranger 2.2', 'harga' => 320000, 'stok' => 11, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO013', 'nama_barang' => 'Upper Tank Ford Ranger 2.5', 'harga' => 420000, 'stok' => 8, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO014', 'nama_barang' => 'Upper Tank Mazda 2 Non-Skyactiv', 'harga' => 220000, 'stok' => 8, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO015', 'nama_barang' => 'Upper Tank Mazda 2 Skyactiv', 'harga' => 150000, 'stok' => 7, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO016', 'nama_barang' => 'Upper Tank Mazda CX5', 'harga' => 320000, 'stok' => 18, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO017', 'nama_barang' => 'Upper Tank Mazda Biante', 'harga' => 310000, 'stok' => 9, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO018', 'nama_barang' => 'Upper Tank Hyundai Avega', 'harga' => 350000, 'stok' => 6, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO019', 'nama_barang' => 'Upper Tank Hyundai Grand Avega', 'harga' => 240000, 'stok' => 15, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO020', 'nama_barang' => 'Upper Tank Hyundai Stargazer', 'harga' => 310000, 'stok' => 16, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO021', 'nama_barang' => 'Upper Tank Hyundai Creta', 'harga' => 270000, 'stok' => 13, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO022', 'nama_barang' => 'Upper Tank Kia Picanto', 'harga' => 220000, 'stok' => 9, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO023', 'nama_barang' => 'Upper Tank Kia Rio', 'harga' => 380000, 'stok' => 5, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO024', 'nama_barang' => 'Upper Tank Kia Sonet', 'harga' => 190000, 'stok' => 17, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO025', 'nama_barang' => 'Upper Tank Chevrolet Spin', 'harga' => 340000, 'stok' => 6, 'batas_minimum' => 3],
            ['kode_barang' => 'RUO026', 'nama_barang' => 'Upper Tank Chevrolet Captiva', 'harga' => 310000, 'stok' => 3, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT001', 'nama_barang' => 'Lower Tank Avanza Lama', 'harga' => 400000, 'stok' => 14, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT002', 'nama_barang' => 'Lower Tank Avanza VVT-i', 'harga' => 160000, 'stok' => 7, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT003', 'nama_barang' => 'Lower Tank Avanza Dual VVT-i', 'harga' => 310000, 'stok' => 4, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT004', 'nama_barang' => 'Lower Tank All New Avanza', 'harga' => 440000, 'stok' => 5, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT005', 'nama_barang' => 'Lower Tank Innova Bensin 2.0', 'harga' => 390000, 'stok' => 8, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT006', 'nama_barang' => 'Lower Tank Innova Diesel 2.5', 'harga' => 430000, 'stok' => 2, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT007', 'nama_barang' => 'Lower Tank Innova Reborn Bensin', 'harga' => 380000, 'stok' => 7, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT008', 'nama_barang' => 'Lower Tank Innova Reborn Diesel', 'harga' => 350000, 'stok' => 20, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT009', 'nama_barang' => 'Lower Tank Innova Zenix', 'harga' => 270000, 'stok' => 20, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT010', 'nama_barang' => 'Lower Tank Fortuner Non-VNT', 'harga' => 310000, 'stok' => 2, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT011', 'nama_barang' => 'Lower Tank Fortuner VNT', 'harga' => 210000, 'stok' => 4, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT012', 'nama_barang' => 'Lower Tank Fortuner VRZ', 'harga' => 390000, 'stok' => 19, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT013', 'nama_barang' => 'Lower Tank Hilux Single Cabin', 'harga' => 170000, 'stok' => 20, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT014', 'nama_barang' => 'Lower Tank Hilux Double Cabin', 'harga' => 380000, 'stok' => 20, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT015', 'nama_barang' => 'Lower Tank Agya 1.0', 'harga' => 450000, 'stok' => 15, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT016', 'nama_barang' => 'Lower Tank Agya 1.2', 'harga' => 350000, 'stok' => 3, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT017', 'nama_barang' => 'Lower Tank Calya 1.2', 'harga' => 270000, 'stok' => 20, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT018', 'nama_barang' => 'Lower Tank Rush Lama', 'harga' => 390000, 'stok' => 21, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT019', 'nama_barang' => 'Lower Tank All New Rush', 'harga' => 380000, 'stok' => 14, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT020', 'nama_barang' => 'Lower Tank Raize 1.0 Turbo', 'harga' => 360000, 'stok' => 16, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT021', 'nama_barang' => 'Lower Tank Raize 1.2', 'harga' => 330000, 'stok' => 15, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT022', 'nama_barang' => 'Lower Tank Yaris Bakpao', 'harga' => 220000, 'stok' => 16, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT023', 'nama_barang' => 'Lower Tank Yaris Lele', 'harga' => 390000, 'stok' => 2, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT024', 'nama_barang' => 'Lower Tank Yaris Joker', 'harga' => 340000, 'stok' => 11, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT025', 'nama_barang' => 'Lower Tank Vios Gen 1', 'harga' => 390000, 'stok' => 15, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT026', 'nama_barang' => 'Lower Tank Vios Gen 2', 'harga' => 180000, 'stok' => 5, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT027', 'nama_barang' => 'Lower Tank Vios Gen 3', 'harga' => 330000, 'stok' => 12, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT028', 'nama_barang' => 'Lower Tank Camry 2.4', 'harga' => 260000, 'stok' => 5, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT029', 'nama_barang' => 'Lower Tank Camry 2.5', 'harga' => 190000, 'stok' => 7, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT030', 'nama_barang' => 'Lower Tank Altis Gen 1', 'harga' => 390000, 'stok' => 13, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT031', 'nama_barang' => 'Lower Tank Altis Gen 2', 'harga' => 250000, 'stok' => 18, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT032', 'nama_barang' => 'Lower Tank Alphard 2.4', 'harga' => 450000, 'stok' => 10, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT033', 'nama_barang' => 'Lower Tank Alphard 2.5', 'harga' => 170000, 'stok' => 9, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT034', 'nama_barang' => 'Lower Tank Vellfire', 'harga' => 420000, 'stok' => 9, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT035', 'nama_barang' => 'Lower Tank Sienta', 'harga' => 270000, 'stok' => 11, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT036', 'nama_barang' => 'Lower Tank Voxy', 'harga' => 310000, 'stok' => 19, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT037', 'nama_barang' => 'Lower Tank Nav1', 'harga' => 410000, 'stok' => 21, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT038', 'nama_barang' => 'Lower Tank Harrier 2.4', 'harga' => 450000, 'stok' => 5, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT039', 'nama_barang' => 'Lower Tank Kijang Super', 'harga' => 280000, 'stok' => 14, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT040', 'nama_barang' => 'Lower Tank Kijang Grand Extra', 'harga' => 230000, 'stok' => 17, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT041', 'nama_barang' => 'Lower Tank Kijang Kapsul 1.8', 'harga' => 450000, 'stok' => 9, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT042', 'nama_barang' => 'Lower Tank Kijang Kapsul 2.0', 'harga' => 340000, 'stok' => 5, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT043', 'nama_barang' => 'Lower Tank Kijang Kapsul Diesel', 'harga' => 280000, 'stok' => 4, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT044', 'nama_barang' => 'Lower Tank Hiace Commuter', 'harga' => 310000, 'stok' => 4, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT045', 'nama_barang' => 'Lower Tank Hiace Premio', 'harga' => 200000, 'stok' => 18, 'batas_minimum' => 3],
            ['kode_barang' => 'RLT046', 'nama_barang' => 'Lower Tank Land Cruiser VX80', 'harga' => 330000, 'stok' => 19, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH001', 'nama_barang' => 'Lower Tank Jazz GD3', 'harga' => 410000, 'stok' => 16, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH002', 'nama_barang' => 'Lower Tank Jazz GE8', 'harga' => 280000, 'stok' => 21, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH003', 'nama_barang' => 'Lower Tank Jazz GK5', 'harga' => 260000, 'stok' => 15, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH004', 'nama_barang' => 'Lower Tank Brio 1.2', 'harga' => 420000, 'stok' => 3, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH005', 'nama_barang' => 'Lower Tank Mobilio', 'harga' => 350000, 'stok' => 3, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH006', 'nama_barang' => 'Lower Tank BRV Lama', 'harga' => 200000, 'stok' => 12, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH007', 'nama_barang' => 'Lower Tank All New BRV', 'harga' => 240000, 'stok' => 15, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH008', 'nama_barang' => 'Lower Tank HRV 1.5', 'harga' => 210000, 'stok' => 3, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH009', 'nama_barang' => 'Lower Tank HRV 1.8', 'harga' => 160000, 'stok' => 10, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH010', 'nama_barang' => 'Lower Tank HRV Turbo', 'harga' => 420000, 'stok' => 18, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH011', 'nama_barang' => 'Lower Tank CRV Gen 1', 'harga' => 240000, 'stok' => 4, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH012', 'nama_barang' => 'Lower Tank CRV Gen 2', 'harga' => 150000, 'stok' => 13, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH013', 'nama_barang' => 'Lower Tank CRV Gen 3 2.0', 'harga' => 300000, 'stok' => 18, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH014', 'nama_barang' => 'Lower Tank CRV Gen 3 2.4', 'harga' => 230000, 'stok' => 18, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH015', 'nama_barang' => 'Lower Tank CRV Gen 4', 'harga' => 400000, 'stok' => 9, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH016', 'nama_barang' => 'Lower Tank CRV Gen 5 Turbo', 'harga' => 410000, 'stok' => 21, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH017', 'nama_barang' => 'Lower Tank Civic Ferio', 'harga' => 270000, 'stok' => 21, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH018', 'nama_barang' => 'Lower Tank Civic FD1', 'harga' => 390000, 'stok' => 15, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH019', 'nama_barang' => 'Lower Tank Civic FD2', 'harga' => 220000, 'stok' => 18, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH020', 'nama_barang' => 'Lower Tank Civic FB', 'harga' => 200000, 'stok' => 21, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH021', 'nama_barang' => 'Lower Tank Civic Turbo FC', 'harga' => 450000, 'stok' => 9, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH022', 'nama_barang' => 'Lower Tank City GD8', 'harga' => 350000, 'stok' => 18, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH023', 'nama_barang' => 'Lower Tank City GM2', 'harga' => 330000, 'stok' => 6, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH024', 'nama_barang' => 'Lower Tank City GM6', 'harga' => 200000, 'stok' => 15, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH025', 'nama_barang' => 'Lower Tank Accord CP2', 'harga' => 390000, 'stok' => 12, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH026', 'nama_barang' => 'Lower Tank Accord CR2', 'harga' => 420000, 'stok' => 12, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH027', 'nama_barang' => 'Lower Tank Freed', 'harga' => 320000, 'stok' => 4, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH028', 'nama_barang' => 'Lower Tank Odyssey RB1', 'harga' => 380000, 'stok' => 13, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH029', 'nama_barang' => 'Lower Tank Odyssey RC1', 'harga' => 280000, 'stok' => 3, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH030', 'nama_barang' => 'Lower Tank Stream 1.7', 'harga' => 400000, 'stok' => 4, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH031', 'nama_barang' => 'Lower Tank Stream 2.0', 'harga' => 410000, 'stok' => 17, 'batas_minimum' => 3],
            ['kode_barang' => 'RLH032', 'nama_barang' => 'Lower Tank Elyson', 'harga' => 390000, 'stok' => 19, 'batas_minimum' => 3],
            ['kode_barang' => 'RLD001', 'nama_barang' => 'Lower Tank Xenia 1.0', 'harga' => 450000, 'stok' => 19, 'batas_minimum' => 3],
            ['kode_barang' => 'RLD002', 'nama_barang' => 'Lower Tank Xenia 1.3', 'harga' => 370000, 'stok' => 11, 'batas_minimum' => 3],
            ['kode_barang' => 'RLD003', 'nama_barang' => 'Lower Tank All New Xenia', 'harga' => 200000, 'stok' => 11, 'batas_minimum' => 3],
            ['kode_barang' => 'RLD004', 'nama_barang' => 'Lower Tank Terios Lama', 'harga' => 250000, 'stok' => 12, 'batas_minimum' => 3],
            ['kode_barang' => 'RLD005', 'nama_barang' => 'Lower Tank All New Terios', 'harga' => 390000, 'stok' => 12, 'batas_minimum' => 3],
            ['kode_barang' => 'RLD006', 'nama_barang' => 'Lower Tank Gran Max 1.3', 'harga' => 440000, 'stok' => 17, 'batas_minimum' => 3],
            ['kode_barang' => 'RLD007', 'nama_barang' => 'Lower Tank Gran Max 1.5', 'harga' => 330000, 'stok' => 10, 'batas_minimum' => 3],
            ['kode_barang' => 'RLD008', 'nama_barang' => 'Lower Tank Luxio', 'harga' => 400000, 'stok' => 5, 'batas_minimum' => 3],
            ['kode_barang' => 'RLD009', 'nama_barang' => 'Lower Tank Ayla 1.0', 'harga' => 290000, 'stok' => 6, 'batas_minimum' => 3],
            ['kode_barang' => 'RLD010', 'nama_barang' => 'Lower Tank Ayla 1.2', 'harga' => 290000, 'stok' => 14, 'batas_minimum' => 3],
            ['kode_barang' => 'RLD011', 'nama_barang' => 'Lower Tank Sigra 1.0', 'harga' => 410000, 'stok' => 16, 'batas_minimum' => 3],
            ['kode_barang' => 'RLD012', 'nama_barang' => 'Lower Tank Sigra 1.2', 'harga' => 260000, 'stok' => 6, 'batas_minimum' => 3],
            ['kode_barang' => 'RLD013', 'nama_barang' => 'Lower Tank Sirion Lama', 'harga' => 430000, 'stok' => 9, 'batas_minimum' => 3],
            ['kode_barang' => 'RLD014', 'nama_barang' => 'Lower Tank All New Sirion', 'harga' => 390000, 'stok' => 13, 'batas_minimum' => 3],
            ['kode_barang' => 'RLD015', 'nama_barang' => 'Lower Tank Taruna Karburator', 'harga' => 420000, 'stok' => 9, 'batas_minimum' => 3],
            ['kode_barang' => 'RLD016', 'nama_barang' => 'Lower Tank Taruna EFI', 'harga' => 350000, 'stok' => 21, 'batas_minimum' => 3],
            ['kode_barang' => 'RLD017', 'nama_barang' => 'Lower Tank Feroza', 'harga' => 390000, 'stok' => 5, 'batas_minimum' => 3],
            ['kode_barang' => 'RLD018', 'nama_barang' => 'Lower Tank Taft GT', 'harga' => 270000, 'stok' => 5, 'batas_minimum' => 3],
            ['kode_barang' => 'RLD019', 'nama_barang' => 'Lower Tank Taft Independent', 'harga' => 450000, 'stok' => 6, 'batas_minimum' => 3],
            ['kode_barang' => 'RLD020', 'nama_barang' => 'Lower Tank Rocky Lama', 'harga' => 310000, 'stok' => 12, 'batas_minimum' => 3],
            ['kode_barang' => 'RLD021', 'nama_barang' => 'Lower Tank Rocky Baru 1.0', 'harga' => 170000, 'stok' => 16, 'batas_minimum' => 3],
            ['kode_barang' => 'RLD022', 'nama_barang' => 'Lower Tank Rocky Baru 1.2', 'harga' => 390000, 'stok' => 9, 'batas_minimum' => 3],
            ['kode_barang' => 'RLD023', 'nama_barang' => 'Lower Tank Zebra 1.3', 'harga' => 230000, 'stok' => 17, 'batas_minimum' => 3],
            ['kode_barang' => 'RLS001', 'nama_barang' => 'Lower Tank Carry 1.0', 'harga' => 240000, 'stok' => 3, 'batas_minimum' => 3],
            ['kode_barang' => 'RLS002', 'nama_barang' => 'Lower Tank Carry Futura 1.5', 'harga' => 280000, 'stok' => 10, 'batas_minimum' => 3],
            ['kode_barang' => 'RLS003', 'nama_barang' => 'Lower Tank New Carry (Tayu)', 'harga' => 410000, 'stok' => 17, 'batas_minimum' => 3],
            ['kode_barang' => 'RLS004', 'nama_barang' => 'Lower Tank APV', 'harga' => 410000, 'stok' => 10, 'batas_minimum' => 3],
            ['kode_barang' => 'RLS005', 'nama_barang' => 'Lower Tank APV Arena', 'harga' => 160000, 'stok' => 6, 'batas_minimum' => 3],
            ['kode_barang' => 'RLS006', 'nama_barang' => 'Lower Tank Ertiga Lama', 'harga' => 310000, 'stok' => 9, 'batas_minimum' => 3],
            ['kode_barang' => 'RLS007', 'nama_barang' => 'Lower Tank All New Ertiga', 'harga' => 260000, 'stok' => 12, 'batas_minimum' => 3],
            ['kode_barang' => 'RLS008', 'nama_barang' => 'Lower Tank XL7', 'harga' => 350000, 'stok' => 17, 'batas_minimum' => 3],
            ['kode_barang' => 'RLS009', 'nama_barang' => 'Lower Tank SX4 X-Over', 'harga' => 300000, 'stok' => 4, 'batas_minimum' => 3],
            ['kode_barang' => 'RLS010', 'nama_barang' => 'Lower Tank SX4 S-Cross', 'harga' => 380000, 'stok' => 14, 'batas_minimum' => 3],
            ['kode_barang' => 'RLS011', 'nama_barang' => 'Lower Tank Grand Vitara 2.0', 'harga' => 200000, 'stok' => 21, 'batas_minimum' => 3],
            ['kode_barang' => 'RLS012', 'nama_barang' => 'Lower Tank Grand Vitara 2.4', 'harga' => 350000, 'stok' => 18, 'batas_minimum' => 3],
            ['kode_barang' => 'RLS013', 'nama_barang' => 'Lower Tank Ignis', 'harga' => 360000, 'stok' => 20, 'batas_minimum' => 3],
            ['kode_barang' => 'RLS014', 'nama_barang' => 'Lower Tank Baleno Lama', 'harga' => 440000, 'stok' => 2, 'batas_minimum' => 3],
            ['kode_barang' => 'RLS015', 'nama_barang' => 'Lower Tank Baleno Hatchback', 'harga' => 380000, 'stok' => 13, 'batas_minimum' => 3],
            ['kode_barang' => 'RLS016', 'nama_barang' => 'Lower Tank Aerio', 'harga' => 230000, 'stok' => 5, 'batas_minimum' => 3],
            ['kode_barang' => 'RLS017', 'nama_barang' => 'Lower Tank Swift ST', 'harga' => 380000, 'stok' => 2, 'batas_minimum' => 3],
            ['kode_barang' => 'RLS018', 'nama_barang' => 'Lower Tank Swift GT3', 'harga' => 200000, 'stok' => 17, 'batas_minimum' => 3],
            ['kode_barang' => 'RLS019', 'nama_barang' => 'Lower Tank Splash', 'harga' => 190000, 'stok' => 13, 'batas_minimum' => 3],
            ['kode_barang' => 'RLS020', 'nama_barang' => 'Lower Tank Jimny Katana', 'harga' => 400000, 'stok' => 15, 'batas_minimum' => 3],
            ['kode_barang' => 'RLS021', 'nama_barang' => 'Lower Tank Jimny JB74', 'harga' => 410000, 'stok' => 20, 'batas_minimum' => 3],
            ['kode_barang' => 'RLS022', 'nama_barang' => 'Lower Tank Karimun Kotak', 'harga' => 450000, 'stok' => 2, 'batas_minimum' => 3],
            ['kode_barang' => 'RLS023', 'nama_barang' => 'Lower Tank Karimun Wagon R', 'harga' => 350000, 'stok' => 18, 'batas_minimum' => 3],
            ['kode_barang' => 'RLM001', 'nama_barang' => 'Lower Tank Xpander', 'harga' => 190000, 'stok' => 11, 'batas_minimum' => 3],
            ['kode_barang' => 'RLM002', 'nama_barang' => 'Lower Tank Xpander Cross', 'harga' => 180000, 'stok' => 11, 'batas_minimum' => 3],
            ['kode_barang' => 'RLM003', 'nama_barang' => 'Lower Tank L300 Bensin', 'harga' => 330000, 'stok' => 8, 'batas_minimum' => 3],
            ['kode_barang' => 'RLM004', 'nama_barang' => 'Lower Tank L300 Diesel', 'harga' => 430000, 'stok' => 15, 'batas_minimum' => 3],
            ['kode_barang' => 'RLM005', 'nama_barang' => 'Lower Tank Pajero Sport Lama', 'harga' => 360000, 'stok' => 20, 'batas_minimum' => 3],
            ['kode_barang' => 'RLM006', 'nama_barang' => 'Lower Tank Pajero Sport Dakar', 'harga' => 450000, 'stok' => 3, 'batas_minimum' => 3],
            ['kode_barang' => 'RLM007', 'nama_barang' => 'Lower Tank All New Pajero Sport', 'harga' => 160000, 'stok' => 8, 'batas_minimum' => 3],
            ['kode_barang' => 'RLM008', 'nama_barang' => 'Lower Tank Outlander Sport', 'harga' => 170000, 'stok' => 17, 'batas_minimum' => 3],
            ['kode_barang' => 'RLM009', 'nama_barang' => 'Lower Tank Triton GLS', 'harga' => 440000, 'stok' => 3, 'batas_minimum' => 3],
            ['kode_barang' => 'RLM010', 'nama_barang' => 'Lower Tank Triton HDX', 'harga' => 440000, 'stok' => 4, 'batas_minimum' => 3],
            ['kode_barang' => 'RLM011', 'nama_barang' => 'Lower Tank Mirage', 'harga' => 320000, 'stok' => 7, 'batas_minimum' => 3],
            ['kode_barang' => 'RLM012', 'nama_barang' => 'Lower Tank Kuda Bensin 1.6', 'harga' => 390000, 'stok' => 10, 'batas_minimum' => 3],
            ['kode_barang' => 'RLM013', 'nama_barang' => 'Lower Tank Kuda Diesel 2.5', 'harga' => 270000, 'stok' => 4, 'batas_minimum' => 3],
            ['kode_barang' => 'RLM014', 'nama_barang' => 'Lower Tank Kuda Grandia 2.0', 'harga' => 300000, 'stok' => 17, 'batas_minimum' => 3],
            ['kode_barang' => 'RLM015', 'nama_barang' => 'Lower Tank Lancer DanGan', 'harga' => 380000, 'stok' => 21, 'batas_minimum' => 3],
            ['kode_barang' => 'RLM016', 'nama_barang' => 'Lower Tank Lancer Evo 3', 'harga' => 430000, 'stok' => 8, 'batas_minimum' => 3],
            ['kode_barang' => 'RLM017', 'nama_barang' => 'Lower Tank Lancer Evo 4', 'harga' => 180000, 'stok' => 21, 'batas_minimum' => 3],
            ['kode_barang' => 'RLM018', 'nama_barang' => 'Lower Tank Galant Hiu', 'harga' => 390000, 'stok' => 18, 'batas_minimum' => 3],
            ['kode_barang' => 'RLM019', 'nama_barang' => 'Lower Tank Colt Diesel Canter', 'harga' => 380000, 'stok' => 14, 'batas_minimum' => 3],
            ['kode_barang' => 'RLN001', 'nama_barang' => 'Lower Tank Grand Livina 1.5', 'harga' => 370000, 'stok' => 13, 'batas_minimum' => 3],
            ['kode_barang' => 'RLN002', 'nama_barang' => 'Lower Tank Grand Livina 1.8', 'harga' => 280000, 'stok' => 13, 'batas_minimum' => 3],
            ['kode_barang' => 'RLN003', 'nama_barang' => 'Lower Tank All New Livina', 'harga' => 190000, 'stok' => 20, 'batas_minimum' => 3],
            ['kode_barang' => 'RLN004', 'nama_barang' => 'Lower Tank March 1.2', 'harga' => 440000, 'stok' => 7, 'batas_minimum' => 3],
            ['kode_barang' => 'RLN005', 'nama_barang' => 'Lower Tank March 1.5', 'harga' => 340000, 'stok' => 17, 'batas_minimum' => 3],
            ['kode_barang' => 'RLN006', 'nama_barang' => 'Lower Tank Datsun Go', 'harga' => 380000, 'stok' => 6, 'batas_minimum' => 3],
            ['kode_barang' => 'RLN007', 'nama_barang' => 'Lower Tank Datsun Go+', 'harga' => 200000, 'stok' => 11, 'batas_minimum' => 3],
            ['kode_barang' => 'RLN008', 'nama_barang' => 'Lower Tank X-Trail T30', 'harga' => 430000, 'stok' => 12, 'batas_minimum' => 3],
            ['kode_barang' => 'RLN009', 'nama_barang' => 'Lower Tank X-Trail T31', 'harga' => 270000, 'stok' => 4, 'batas_minimum' => 3],
            ['kode_barang' => 'RLN010', 'nama_barang' => 'Lower Tank X-Trail T32', 'harga' => 320000, 'stok' => 12, 'batas_minimum' => 3],
            ['kode_barang' => 'RLN011', 'nama_barang' => 'Lower Tank Serena C24', 'harga' => 150000, 'stok' => 3, 'batas_minimum' => 3],
            ['kode_barang' => 'RLN012', 'nama_barang' => 'Lower Tank Serena C26', 'harga' => 150000, 'stok' => 19, 'batas_minimum' => 3],
            ['kode_barang' => 'RLN013', 'nama_barang' => 'Lower Tank Evalia', 'harga' => 230000, 'stok' => 6, 'batas_minimum' => 3],
            ['kode_barang' => 'RLN014', 'nama_barang' => 'Lower Tank Juke', 'harga' => 400000, 'stok' => 19, 'batas_minimum' => 3],
            ['kode_barang' => 'RLN015', 'nama_barang' => 'Lower Tank Navara D40', 'harga' => 300000, 'stok' => 8, 'batas_minimum' => 3],
            ['kode_barang' => 'RLN016', 'nama_barang' => 'Lower Tank Navara NP300', 'harga' => 300000, 'stok' => 4, 'batas_minimum' => 3],
            ['kode_barang' => 'RLN017', 'nama_barang' => 'Lower Tank Terrano', 'harga' => 390000, 'stok' => 5, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO001', 'nama_barang' => 'Lower Tank Isuzu Panther 2.3', 'harga' => 210000, 'stok' => 9, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO002', 'nama_barang' => 'Lower Tank Isuzu Panther 2.5', 'harga' => 290000, 'stok' => 7, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO003', 'nama_barang' => 'Lower Tank Isuzu Elf NKR', 'harga' => 450000, 'stok' => 10, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO004', 'nama_barang' => 'Lower Tank Isuzu MU-X', 'harga' => 270000, 'stok' => 4, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO005', 'nama_barang' => 'Lower Tank Wuling Confero', 'harga' => 370000, 'stok' => 12, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO006', 'nama_barang' => 'Lower Tank Wuling Cortez', 'harga' => 350000, 'stok' => 3, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO007', 'nama_barang' => 'Lower Tank Wuling Almaz', 'harga' => 280000, 'stok' => 9, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO008', 'nama_barang' => 'Lower Tank Wuling Formo', 'harga' => 260000, 'stok' => 5, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO009', 'nama_barang' => 'Lower Tank Ford Fiesta 1.4', 'harga' => 380000, 'stok' => 6, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO010', 'nama_barang' => 'Lower Tank Ford Fiesta 1.5', 'harga' => 270000, 'stok' => 20, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO011', 'nama_barang' => 'Lower Tank Ford Everest', 'harga' => 220000, 'stok' => 12, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO012', 'nama_barang' => 'Lower Tank Ford Ranger 2.2', 'harga' => 330000, 'stok' => 12, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO013', 'nama_barang' => 'Lower Tank Ford Ranger 2.5', 'harga' => 170000, 'stok' => 12, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO014', 'nama_barang' => 'Lower Tank Mazda 2 Non-Skyactiv', 'harga' => 350000, 'stok' => 16, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO015', 'nama_barang' => 'Lower Tank Mazda 2 Skyactiv', 'harga' => 240000, 'stok' => 8, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO016', 'nama_barang' => 'Lower Tank Mazda CX5', 'harga' => 400000, 'stok' => 20, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO017', 'nama_barang' => 'Lower Tank Mazda Biante', 'harga' => 440000, 'stok' => 2, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO018', 'nama_barang' => 'Lower Tank Hyundai Avega', 'harga' => 190000, 'stok' => 4, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO019', 'nama_barang' => 'Lower Tank Hyundai Grand Avega', 'harga' => 430000, 'stok' => 21, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO020', 'nama_barang' => 'Lower Tank Hyundai Stargazer', 'harga' => 260000, 'stok' => 11, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO021', 'nama_barang' => 'Lower Tank Hyundai Creta', 'harga' => 380000, 'stok' => 9, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO022', 'nama_barang' => 'Lower Tank Kia Picanto', 'harga' => 420000, 'stok' => 9, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO023', 'nama_barang' => 'Lower Tank Kia Rio', 'harga' => 260000, 'stok' => 6, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO024', 'nama_barang' => 'Lower Tank Kia Sonet', 'harga' => 390000, 'stok' => 7, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO025', 'nama_barang' => 'Lower Tank Chevrolet Spin', 'harga' => 220000, 'stok' => 3, 'batas_minimum' => 3],
            ['kode_barang' => 'RLO026', 'nama_barang' => 'Lower Tank Chevrolet Captiva', 'harga' => 230000, 'stok' => 5, 'batas_minimum' => 3],
            ['kode_barang' => 'CLU001', 'nama_barang' => 'Coolant Prestone Merah 4L', 'harga' => 125000, 'stok' => 54, 'batas_minimum' => 10],
            ['kode_barang' => 'CLU002', 'nama_barang' => 'Coolant Prestone Hijau 4L', 'harga' => 125000, 'stok' => 13, 'batas_minimum' => 10],
            ['kode_barang' => 'CLU003', 'nama_barang' => 'Coolant Top1 Merah 1L', 'harga' => 35000, 'stok' => 36, 'batas_minimum' => 10],
            ['kode_barang' => 'CLU004', 'nama_barang' => 'Coolant Top1 Hijau 1L', 'harga' => 35000, 'stok' => 55, 'batas_minimum' => 10],
            ['kode_barang' => 'CLU005', 'nama_barang' => 'Coolant Megacools Hijau 1L', 'harga' => 25000, 'stok' => 41, 'batas_minimum' => 10],
            ['kode_barang' => 'CLU006', 'nama_barang' => 'Coolant Megacools Merah 1L', 'harga' => 25000, 'stok' => 28, 'batas_minimum' => 10],
            ['kode_barang' => 'CLU007', 'nama_barang' => 'Air Radiator Aquadest 5L', 'harga' => 20000, 'stok' => 88, 'batas_minimum' => 10],
            ['kode_barang' => 'CLU008', 'nama_barang' => 'Coolant Wurth Biru 5L', 'harga' => 200000, 'stok' => 16, 'batas_minimum' => 10],
            ['kode_barang' => 'CLU009', 'nama_barang' => 'Coolant Jumbo Hijau 4L', 'harga' => 80000, 'stok' => 20, 'batas_minimum' => 10],
            ['kode_barang' => 'CLT001', 'nama_barang' => 'Toyota Motor Oil (TMO) Coolant Merah 4L', 'harga' => 160000, 'stok' => 43, 'batas_minimum' => 10],
            ['kode_barang' => 'CLT002', 'nama_barang' => 'Toyota Motor Oil (TMO) Coolant Merah 1L', 'harga' => 45000, 'stok' => 23, 'batas_minimum' => 10],
            ['kode_barang' => 'CLH001', 'nama_barang' => 'Honda Radiator Coolant Type 2 (Biru) 4L', 'harga' => 175000, 'stok' => 26, 'batas_minimum' => 10],
            ['kode_barang' => 'CLH002', 'nama_barang' => 'Honda Radiator Coolant Type 1 (Hijau) 4L', 'harga' => 165000, 'stok' => 72, 'batas_minimum' => 10],
            ['kode_barang' => 'CLH003', 'nama_barang' => 'Honda Radiator Coolant (Biru) 1L', 'harga' => 50000, 'stok' => 30, 'batas_minimum' => 10],
            ['kode_barang' => 'CLD001', 'nama_barang' => 'Daihatsu Genuine Coolant Merah 4L', 'harga' => 155000, 'stok' => 78, 'batas_minimum' => 10],
            ['kode_barang' => 'CLS001', 'nama_barang' => 'Suzuki Ecstar Coolant Biru 4L', 'harga' => 150000, 'stok' => 72, 'batas_minimum' => 10],
            ['kode_barang' => 'CLS002', 'nama_barang' => 'Suzuki Ecstar Coolant Biru 1L', 'harga' => 40000, 'stok' => 13, 'batas_minimum' => 10],
            ['kode_barang' => 'CLM001', 'nama_barang' => 'Mitsubishi Motors Genuine Coolant Hijau 4L', 'harga' => 180000, 'stok' => 55, 'batas_minimum' => 10],
            ['kode_barang' => 'CLM002', 'nama_barang' => 'Mitsubishi Motors Genuine Coolant Hijau 1L', 'harga' => 55000, 'stok' => 40, 'batas_minimum' => 10],
            ['kode_barang' => 'CLN001', 'nama_barang' => 'Nissan Genuine Coolant Biru 4L', 'harga' => 170000, 'stok' => 69, 'batas_minimum' => 10],
            ['kode_barang' => 'JSU001', 'nama_barang' => 'Isi Freon AC (Jasa + Freon R134a Full)', 'harga' => 200000, 'stok' => 992, 'batas_minimum' => 0],
            ['kode_barang' => 'JSU002', 'nama_barang' => 'Tambah Freon AC (Setengah)', 'harga' => 100000, 'stok' => 999, 'batas_minimum' => 0],
            ['kode_barang' => 'JSU003', 'nama_barang' => 'Jasa Korok Radiator Mobil Kecil', 'harga' => 150000, 'stok' => 993, 'batas_minimum' => 0],
            ['kode_barang' => 'JSU004', 'nama_barang' => 'Jasa Korok Radiator Mobil Besar/Truk', 'harga' => 250000, 'stok' => 997, 'batas_minimum' => 0],
            ['kode_barang' => 'JSU008', 'nama_barang' => 'Jasa Ganti Upper/Lower Tank (Termasuk Lem)', 'harga' => 100000, 'stok' => 998, 'batas_minimum' => 0],
            ['kode_barang' => 'OLI-001', 'nama_barang' => 'Oli Mesin TMO 10W-40', 'harga' => 85000, 'stok' => 15, 'batas_minimum' => 5],

        ]);

        DB::table('distributor')->insert([
            ['id_distributor' => 'D001', 'nama_distributor' => 'PT Astra Honda', 'alamat' => 'Jl. Jenderal Sudirman', 'no_hp' => '08111222333', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]
        ]);

        DB::table('chatbot_rule')->insert([
            ['keyword' => 'berapa', 'action_type' => 'check_price', 'response_text' => null],
            ['keyword' => 'harga', 'action_type' => 'check_price', 'response_text' => null],
            ['keyword' => 'biaya', 'action_type' => 'check_price', 'response_text' => null],
            ['keyword' => 'stok', 'action_type' => 'check_stock', 'response_text' => null],
            ['keyword' => 'sisa', 'action_type' => 'check_stock', 'response_text' => null],
            ['keyword' => 'ada', 'action_type' => 'check_stock', 'response_text' => null],
            ['keyword' => 'halo', 'action_type' => 'text', 'response_text' => 'Halo! Saya Asisten Virtual Doles Radiator. Ada yang bisa saya bantu hari ini? Anda bisa tanya "berapa harga radiator" atau "jam berapa bengkel buka".'],
            ['keyword' => 'hai', 'action_type' => 'text', 'response_text' => 'Hai! Selamat datang di layanan asisten pintar Doles Radiator. Silakan tanyakan keluhan mobil Anda atau info stok barang yang Anda butuhkan.'],
            ['keyword' => 'pagi', 'action_type' => 'text', 'response_text' => 'Selamat pagi! Bengkel Doles Radiator siap melayani kendaraan Anda. Ada yang mau ditanyakan soal servis atau stok barang?'],
            ['keyword' => 'siang', 'action_type' => 'text', 'response_text' => 'Selamat siang! Silakan tanyakan apa saja seputar servis atau stok suku cadang, asisten Doles Radiator siap membantu.'],
            ['keyword' => 'malam', 'action_type' => 'text', 'response_text' => 'Selamat malam! Saat ini bengkel kami sudah tutup (buka 08:00 - 18:00), tapi Anda tetap bisa bertanya soal estimasi harga barang atau info servis di sini.'],
            ['keyword' => 'buka', 'action_type' => 'text', 'response_text' => 'Bengkel Doles Radiator buka setiap hari Senin - Sabtu, mulai jam 08:00 WIB sampai dengan 18:00 WIB. Hari Minggu kami libur ya.'],
            ['keyword' => 'jam tutup', 'action_type' => 'text', 'response_text' => 'Kami tutup pada jam 18:00 WIB dan libur setiap hari Minggu. Silakan datang di jam operasional kami!'],
            ['keyword' => 'jam', 'action_type' => 'text', 'response_text' => 'Jam operasional kami: Senin-Sabtu (08:00 - 18:00 WIB). Hari Minggu libur.'],
            ['keyword' => 'alamat', 'action_type' => 'text', 'response_text' => 'Lokasi bengkel kami berada di Jl. Pembangunan, Lorong Himalaya, Banda Aceh. Anda bisa ketik "Doles Radiator" di Google Maps biar lebih gampang!'],
            ['keyword' => 'lokasi', 'action_type' => 'text', 'response_text' => 'Kami berlokasi di Jl. Pembangunan, Lorong Himalaya, Banda Aceh. Ditunggu kedatangannya ya!'],
            ['keyword' => 'posisi', 'action_type' => 'text', 'response_text' => 'Posisi bengkel ada di Jl. Pembangunan, Lorong Himalaya, Banda Aceh.'],
            ['keyword' => 'garansi', 'action_type' => 'text', 'response_text' => 'Semua pengerjaan servis di tempat kami mendapatkan garansi! Jangan lupa simpan nomor resi/tracking Anda untuk mengecek status garansi lewat website ini.'],
            ['keyword' => 'klaim', 'action_type' => 'text', 'response_text' => 'Untuk klaim garansi, silakan bawa kendaraan kembali ke bengkel kami dan tunjukkan status servis dari halaman website kami yang menyatakan garansi Anda masih "Aktif".'],
            ['keyword' => 'terima kasih', 'action_type' => 'text', 'response_text' => 'Sama-sama! Semoga informasi yang diberikan bermanfaat. Jangan ragu hubungi kami lagi jika ada masalah suhu mesin ya!'],
            ['keyword' => 'makasih', 'action_type' => 'text', 'response_text' => 'Sama-sama kak! Sehat selalu dan rawat terus kendaraan kesayangannya ya!'],
            ['keyword' => 'oke', 'action_type' => 'text', 'response_text' => 'Siap! Jika masih ada yang kurang jelas, silakan tanyakan lagi atau langsung Whatsapp admin kami.'],
            ['keyword' => 'bocor', 'action_type' => 'text', 'response_text' => 'Radiator bocor itu bahaya! Jangan dipaksa jalan jika air radiator cepat habis. Bawa saja mobilnya langsung ke bengkel agar dicek dan dilas (tambal) oleh ahlinya.'],
            ['keyword' => 'overheat', 'action_type' => 'text', 'response_text' => 'Jangan dipaksa kalau mesin sering overheat! Segera menepi, matikan mesin, lalu bawa ke Doles Radiator. Kami akan menguras dan mendeteksi sumbatan di sistem pendingin Anda.'],
            ['keyword' => 'panas', 'action_type' => 'text', 'response_text' => 'Jika jarum temperatur nyaris mentok merah atau mobil terasa sangat panas, itu tanda sirkulasi pendingin ngadat. Segera jadwalkan pengecekan di bengkel kami.'],
            ['keyword' => 'kontak', 'action_type' => 'text', 'response_text' => 'Anda bisa langsung menghubungi admin atau mekanik kami lewat Whatsapp/Telepon di nomor: 0821-6344-4129.'],
            ['keyword' => 'no hp', 'action_type' => 'text', 'response_text' => 'Silakan hubungi atau Whatsapp ke nomor 081230970997 ya kak.'],
            ['keyword' => 'wa', 'action_type' => 'text', 'response_text' => 'Nomor WhatsApp resmi Doles Radiator adalah 081230970997'],
            ['keyword' => 'padum', 'action_type' => 'check_price', 'response_text' => null],
            ['keyword' => 'assalamualaikum', 'action_type' => 'text', 'response_text' => 'Waalaikumsalam warahmatullah. Selamat datang di Doles Radiator. Ada yang bisa kami bantu terkait perbaikan radiator atau AC Anda?'],
            ['keyword' => 'dimana', 'action_type' => 'text', 'response_text' => 'Bengkel Doles Radiator berlokasi di Jl. Pembangunan lorong himalaya, Peunayong, Kec. Kuta Alam, Kota Banda Aceh.'],
            ['keyword' => 'habis', 'action_type' => 'text', 'response_text' => 'Air radiator yang cepat habis menandakan adanya kebocoran atau penguapan berlebih (overheat). Segera periksa slang, tutup radiator, atau bawa ke bengkel kami untuk di-cek tekanannya.'],
            ['keyword' => 'amper', 'action_type' => 'text', 'response_text' => 'Amper suhu mobil yang naik mendekati atau mencapai batas H (High) adalah tanda mesin overheat (terlalu panas). Segera menepi dan matikan mesin. Jika butuh bantuan pengecekan, hubungi kami di WA 0812-3097-0997.'],
            ['keyword' => 'kotor', 'action_type' => 'text', 'response_text' => 'Air radiator yang kotor, keruh, atau berwarna karat tebal berarti sirkulasi tidak lancar. Kami sangat menyarankan Anda mengambil jasa servis Korok Radiator agar saluran pendingin bersih seperti baru.'],
            ['keyword' => 'mampet', 'action_type' => 'text', 'response_text' => 'Radiator yang mampet bisa dikorok (dibersihkan salurannya satu per satu). Bawa kendaraan Anda ke Doles Radiator, kami ahli dalam jasa servis korok radiator mobil kecil maupun truk/alat berat.'],
            ['keyword' => 'ac', 'action_type' => 'text', 'response_text' => 'Selain spesialis radiator, bengkel kami juga melayani servis AC mobil, seperti pengecekan kebocoran, isi freon R134a, dan pembersihan kondensor AC.'],
            ['keyword' => 'freon', 'action_type' => 'text', 'response_text' => 'AC mobil kurang dingin? Kami menyediakan layanan pengisian Freon R134a dan pengecekan kebocoran kompresor AC Anda. Silakan bawa mobilnya ke bengkel untuk dicek.'],
            ['keyword' => 'piro', 'action_type' => 'check_price', 'response_text' => null],
            ['keyword' => 'ready', 'action_type' => 'check_stock', 'response_text' => null],
            ['keyword' => 'amper panas', 'action_type' => 'text', 'response_text' => 'Jika indikator amper suhu mesin mobil Anda naik (panas) dan air radiator habis, kemungkinan besar ada kebocoran pada sistem pendingin atau kipas mati. Sebaiknya segera hentikan mobil agar mesin tidak jebol (overheat) dan bawa ke bengkel kami untuk pengecekan.'],
            ['keyword' => 'ganti', 'action_type' => 'text', 'response_text' => 'Komponen yang sering diganti saat radiator bermasalah biasanya adalah Upper/Lower Tank (jika retak atau pecah), selang radiator, thermostat, atau terkadang cukup kuras air radiator (korok) saja. Untuk pastinya, sebaiknya dicek langsung di bengkel.'],
            ['keyword' => 'masalah', 'action_type' => 'text', 'response_text' => 'Masalah pada sistem pendingin biasanya bermacam-macam, mulai dari kipas mati, radiator mampet, selang bocor, hingga waterpump rusak. Bawa mobil Anda ke Doles Radiator agar kami bisa mendiagnosa masalah pastinya!'],
            ['keyword' => 'kenapa', 'action_type' => 'text', 'response_text' => 'Mesin overheat atau sering tambah air biasanya karena ada jalur sirkulasi pendingin yang bocor atau tersumbat kotoran. Jika dibiarkan bisa turun mesin lho! Yuk, cek di Doles Radiator.'],
            ['keyword' => 'pergantian', 'action_type' => 'text', 'response_text' => 'Komponen yang sering diganti saat radiator bermasalah biasanya adalah Upper/Lower Tank (jika retak atau pecah), selang radiator, thermostat, atau terkadang cukup kuras air radiator (korok) saja. Untuk pastinya, sebaiknya dicek langsung di bengkel.'],
            ['keyword' => 'diganti', 'action_type' => 'text', 'response_text' => 'Komponen yang sering diganti saat radiator bermasalah biasanya adalah Upper/Lower Tank (jika retak atau pecah), selang radiator, thermostat, atau terkadang cukup kuras air radiator (korok) saja. Untuk pastinya, sebaiknya dicek langsung di bengkel.'],
            ['keyword' => 'tutup atas', 'action_type' => 'text', 'response_text' => 'Jika kebocoran terjadi pada tutup atas radiator (upper tank), solusinya adalah mengganti upper tank tersebut dengan yang baru agar air tidak merembes keluar saat mesin panas. Anda bisa membawa mobilnya kemari untuk kami ganti upper tank-nya.'],
            ['keyword' => 'bocor di tutup', 'action_type' => 'text', 'response_text' => 'Jika kebocoran terjadi pada tutup atas radiator (upper tank), solusinya adalah mengganti upper tank tersebut dengan yang baru agar air tidak merembes keluar saat mesin panas. Anda bisa membawa mobilnya kemari untuk kami ganti upper tank-nya.'],
            ['keyword' => 'spil', 'action_type' => 'check_stock', 'response_text' => null],
            ['keyword' => 'jam buka', 'action_type' => 'text', 'response_text' => 'Doles Radiator buka setiap hari Senin hingga Sabtu mulai pukul 08:00 hingga 18:00 WIB. Hari Minggu kami libur.'],

        ]);

        DB::table('service')->insert([
            ['id_service' => 'S001', 'id_kendaraan' => 'M001', 'id_karyawan' => 'K002', 'invoice_number' => 'INV-202610-001', 'status' => 'Diproses', 'total_biaya' => 200000, 'catatan' => 'Radiator bocor', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]
        ]);
        
        DB::table('service_detail')->insert([
            ['id_service' => 'S001', 'kode_barang' => 'RUT001', 'qty' => 1, 'subtotal' => 290000, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]
        ]);
    }
}
