<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Sparepart;
use App\Models\Pelanggan;

class DummyDataSeeder extends Seeder
{
    public function run(): void
    {
        // 1. DATA PELANGGAN
        $pelanggan = [
            ['nama' => 'Bpk. Andi', 'nomor_hp' => '081234567890'],
            ['nama' => 'Ibu Ratna', 'nomor_hp' => '081298765432'],
            ['nama' => 'Bpk. Budi Santoso', 'nomor_hp' => '085712349876'],
            ['nama' => 'Mas Dimas', 'nomor_hp' => '081345678901'],
            ['nama' => 'Mbak Sari', 'nomor_hp' => '081912345678'],
        ];

        foreach ($pelanggan as $p) {
            Pelanggan::firstOrCreate(['nomor_hp' => $p['nomor_hp']], $p);
        }

        // 2. DATA KENDARAAN
        $kendaraan = [
            ['nomor_polisi' => 'B 1234 ABC', 'pelanggan_id' => 1, 'model' => 'Toyota Avanza'],
            ['nomor_polisi' => 'D 5678 DEF', 'pelanggan_id' => 2, 'model' => 'Honda Brio'],
            ['nomor_polisi' => 'F 9012 GHI', 'pelanggan_id' => 3, 'model' => 'Mitsubishi Xpander'],
            ['nomor_polisi' => 'B 3456 JKL', 'pelanggan_id' => 4, 'model' => 'Toyota Innova Reborn'],
            ['nomor_polisi' => 'A 7890 MNO', 'pelanggan_id' => 5, 'model' => 'Daihatsu Sigra'],
        ];

        foreach ($kendaraan as $k) {
            $k['nomor_polisi'] = strtoupper(str_replace(' ', '', $k['nomor_polisi']));
            \App\Models\Kendaraan::firstOrCreate(['nomor_polisi' => $k['nomor_polisi']], $k);
        }

        // 2. DATA SPAREPART & JASA (Sesuai Excel 120+ Item)
                $sparepart = [
            // ================= RADIATOR UPPER TANK =================
            ['nama_barang' => '[RUT001] Upper Tank Avanza Lama', 'batas_minimum' => 3, 'harga' => 290000, 'stok_sekarang' => 18],
            ['nama_barang' => '[RUT002] Upper Tank Avanza VVT-i', 'batas_minimum' => 3, 'harga' => 170000, 'stok_sekarang' => 11],
            ['nama_barang' => '[RUT003] Upper Tank Avanza Dual VVT-i', 'batas_minimum' => 3, 'harga' => 320000, 'stok_sekarang' => 4],
            ['nama_barang' => '[RUT004] Upper Tank All New Avanza', 'batas_minimum' => 3, 'harga' => 420000, 'stok_sekarang' => 19],
            ['nama_barang' => '[RUT005] Upper Tank Innova Bensin 2.0', 'batas_minimum' => 3, 'harga' => 170000, 'stok_sekarang' => 10],
            ['nama_barang' => '[RUT006] Upper Tank Innova Diesel 2.5', 'batas_minimum' => 3, 'harga' => 330000, 'stok_sekarang' => 2],
            ['nama_barang' => '[RUT007] Upper Tank Innova Reborn Bensin', 'batas_minimum' => 3, 'harga' => 290000, 'stok_sekarang' => 17],
            ['nama_barang' => '[RUT008] Upper Tank Innova Reborn Diesel', 'batas_minimum' => 3, 'harga' => 430000, 'stok_sekarang' => 8],
            ['nama_barang' => '[RUT009] Upper Tank Innova Zenix', 'batas_minimum' => 3, 'harga' => 440000, 'stok_sekarang' => 16],
            ['nama_barang' => '[RUT010] Upper Tank Fortuner Non-VNT', 'batas_minimum' => 3, 'harga' => 190000, 'stok_sekarang' => 3],
            ['nama_barang' => '[RUT011] Upper Tank Fortuner VNT', 'batas_minimum' => 3, 'harga' => 440000, 'stok_sekarang' => 3],
            ['nama_barang' => '[RUT012] Upper Tank Fortuner VRZ', 'batas_minimum' => 3, 'harga' => 170000, 'stok_sekarang' => 8],
            ['nama_barang' => '[RUT013] Upper Tank Hilux Single Cabin', 'batas_minimum' => 3, 'harga' => 270000, 'stok_sekarang' => 16],
            ['nama_barang' => '[RUT014] Upper Tank Hilux Double Cabin', 'batas_minimum' => 3, 'harga' => 150000, 'stok_sekarang' => 9],
            ['nama_barang' => '[RUT015] Upper Tank Agya 1.0', 'batas_minimum' => 3, 'harga' => 440000, 'stok_sekarang' => 10],
            ['nama_barang' => '[RUT016] Upper Tank Agya 1.2', 'batas_minimum' => 3, 'harga' => 160000, 'stok_sekarang' => 19],
            ['nama_barang' => '[RUT017] Upper Tank Calya 1.2', 'batas_minimum' => 3, 'harga' => 390000, 'stok_sekarang' => 9],
            ['nama_barang' => '[RUT018] Upper Tank Rush Lama', 'batas_minimum' => 3, 'harga' => 230000, 'stok_sekarang' => 10],
            ['nama_barang' => '[RUT019] Upper Tank All New Rush', 'batas_minimum' => 3, 'harga' => 220000, 'stok_sekarang' => 13],
            ['nama_barang' => '[RUT020] Upper Tank Raize 1.0 Turbo', 'batas_minimum' => 3, 'harga' => 190000, 'stok_sekarang' => 8],
            ['nama_barang' => '[RUT021] Upper Tank Raize 1.2', 'batas_minimum' => 3, 'harga' => 340000, 'stok_sekarang' => 11],
            ['nama_barang' => '[RUT022] Upper Tank Yaris Bakpao', 'batas_minimum' => 3, 'harga' => 340000, 'stok_sekarang' => 12],
            ['nama_barang' => '[RUT023] Upper Tank Yaris Lele', 'batas_minimum' => 3, 'harga' => 170000, 'stok_sekarang' => 14],
            ['nama_barang' => '[RUT024] Upper Tank Yaris Joker', 'batas_minimum' => 3, 'harga' => 450000, 'stok_sekarang' => 4],
            ['nama_barang' => '[RUT025] Upper Tank Vios Gen 1', 'batas_minimum' => 3, 'harga' => 400000, 'stok_sekarang' => 14],
            ['nama_barang' => '[RUT026] Upper Tank Vios Gen 2', 'batas_minimum' => 3, 'harga' => 210000, 'stok_sekarang' => 4],
            ['nama_barang' => '[RUT027] Upper Tank Vios Gen 3', 'batas_minimum' => 3, 'harga' => 260000, 'stok_sekarang' => 18],
            ['nama_barang' => '[RUT028] Upper Tank Camry 2.4', 'batas_minimum' => 3, 'harga' => 170000, 'stok_sekarang' => 21],
            ['nama_barang' => '[RUT029] Upper Tank Camry 2.5', 'batas_minimum' => 3, 'harga' => 280000, 'stok_sekarang' => 2],
            ['nama_barang' => '[RUT030] Upper Tank Altis Gen 1', 'batas_minimum' => 3, 'harga' => 250000, 'stok_sekarang' => 4],
            ['nama_barang' => '[RUT031] Upper Tank Altis Gen 2', 'batas_minimum' => 3, 'harga' => 190000, 'stok_sekarang' => 13],
            ['nama_barang' => '[RUT032] Upper Tank Alphard 2.4', 'batas_minimum' => 3, 'harga' => 450000, 'stok_sekarang' => 5],
            ['nama_barang' => '[RUT033] Upper Tank Alphard 2.5', 'batas_minimum' => 3, 'harga' => 380000, 'stok_sekarang' => 7],
            ['nama_barang' => '[RUT034] Upper Tank Vellfire', 'batas_minimum' => 3, 'harga' => 240000, 'stok_sekarang' => 12],
            ['nama_barang' => '[RUT035] Upper Tank Sienta', 'batas_minimum' => 3, 'harga' => 430000, 'stok_sekarang' => 16],
            ['nama_barang' => '[RUT036] Upper Tank Voxy', 'batas_minimum' => 3, 'harga' => 200000, 'stok_sekarang' => 4],
            // ================= Core Radiator =================
            ['nama_barang' => '[RCT001] Core Radiator Avanza Manual 1ply', 'batas_minimum' => 2, 'harga' => 600000, 'stok_sekarang' => 5],
            ['nama_barang' => '[RCT002] Core Radiator Innova Bensin Manual', 'batas_minimum' => 1, 'harga' => 850000, 'stok_sekarang' => 3],
            ['nama_barang' => '[RCM001] Core Radiator L300 Diesel Kuningan', 'batas_minimum' => 2, 'harga' => 1200000, 'stok_sekarang' => 4],
            ['nama_barang' => '[RCO001] Core Radiator Panther Kuningan', 'batas_minimum' => 3, 'harga' => 1100000, 'stok_sekarang' => 3],
            ['nama_barang' => '[RCN001] Core Radiator Grand Livina Matic', 'batas_minimum' => 2, 'harga' => 750000, 'stok_sekarang' => 2],
            ['nama_barang' => '[RCS001] Core Radiator Futura / Carry', 'batas_minimum' => 6, 'harga' => 550000, 'stok_sekarang' => 6],
            ['nama_barang' => '[RUT037] Upper Tank Nav1', 'batas_minimum' => 3, 'harga' => 250000, 'stok_sekarang' => 8],
            ['nama_barang' => '[RUT038] Upper Tank Harrier 2.4', 'batas_minimum' => 3, 'harga' => 160000, 'stok_sekarang' => 9],
            ['nama_barang' => '[RUT039] Upper Tank Kijang Super', 'batas_minimum' => 3, 'harga' => 220000, 'stok_sekarang' => 12],
            ['nama_barang' => '[RUT040] Upper Tank Kijang Grand Extra', 'batas_minimum' => 3, 'harga' => 370000, 'stok_sekarang' => 11],
            ['nama_barang' => '[RUT041] Upper Tank Kijang Kapsul 1.8', 'batas_minimum' => 3, 'harga' => 150000, 'stok_sekarang' => 9],
            ['nama_barang' => '[RUT042] Upper Tank Kijang Kapsul 2.0', 'batas_minimum' => 3, 'harga' => 200000, 'stok_sekarang' => 10],
            ['nama_barang' => '[RUT043] Upper Tank Kijang Kapsul Diesel', 'batas_minimum' => 3, 'harga' => 380000, 'stok_sekarang' => 16],
            ['nama_barang' => '[RUT044] Upper Tank Hiace Commuter', 'batas_minimum' => 3, 'harga' => 410000, 'stok_sekarang' => 21],
            ['nama_barang' => '[RUT045] Upper Tank Hiace Premio', 'batas_minimum' => 3, 'harga' => 230000, 'stok_sekarang' => 20],
            ['nama_barang' => '[RUT046] Upper Tank Land Cruiser VX80', 'batas_minimum' => 3, 'harga' => 240000, 'stok_sekarang' => 19],
            ['nama_barang' => '[RUH001] Upper Tank Jazz GD3', 'batas_minimum' => 3, 'harga' => 290000, 'stok_sekarang' => 12],
            ['nama_barang' => '[RUH002] Upper Tank Jazz GE8', 'batas_minimum' => 3, 'harga' => 270000, 'stok_sekarang' => 17],
            ['nama_barang' => '[RUH003] Upper Tank Jazz GK5', 'batas_minimum' => 3, 'harga' => 180000, 'stok_sekarang' => 17],
            ['nama_barang' => '[RUH004] Upper Tank Brio 1.2', 'batas_minimum' => 3, 'harga' => 360000, 'stok_sekarang' => 8],
            ['nama_barang' => '[RUH005] Upper Tank Mobilio', 'batas_minimum' => 3, 'harga' => 420000, 'stok_sekarang' => 16],
            ['nama_barang' => '[RUH006] Upper Tank BRV Lama', 'batas_minimum' => 3, 'harga' => 150000, 'stok_sekarang' => 14],
            ['nama_barang' => '[RUH007] Upper Tank All New BRV', 'batas_minimum' => 3, 'harga' => 160000, 'stok_sekarang' => 7],
            ['nama_barang' => '[RUH008] Upper Tank HRV 1.5', 'batas_minimum' => 3, 'harga' => 440000, 'stok_sekarang' => 15],
            ['nama_barang' => '[RUH009] Upper Tank HRV 1.8', 'batas_minimum' => 3, 'harga' => 160000, 'stok_sekarang' => 16],
            ['nama_barang' => '[RUH010] Upper Tank HRV Turbo', 'batas_minimum' => 3, 'harga' => 320000, 'stok_sekarang' => 6],
            ['nama_barang' => '[RUH011] Upper Tank CRV Gen 1', 'batas_minimum' => 3, 'harga' => 360000, 'stok_sekarang' => 14],
            ['nama_barang' => '[RUH012] Upper Tank CRV Gen 2', 'batas_minimum' => 3, 'harga' => 360000, 'stok_sekarang' => 2],
            ['nama_barang' => '[RUH013] Upper Tank CRV Gen 3 2.0', 'batas_minimum' => 3, 'harga' => 370000, 'stok_sekarang' => 13],
            ['nama_barang' => '[RUH014] Upper Tank CRV Gen 3 2.4', 'batas_minimum' => 3, 'harga' => 290000, 'stok_sekarang' => 3],
            ['nama_barang' => '[RUH015] Upper Tank CRV Gen 4', 'batas_minimum' => 3, 'harga' => 390000, 'stok_sekarang' => 19],
            ['nama_barang' => '[RUH016] Upper Tank CRV Gen 5 Turbo', 'batas_minimum' => 3, 'harga' => 190000, 'stok_sekarang' => 8],
            ['nama_barang' => '[RUH017] Upper Tank Civic Ferio', 'batas_minimum' => 3, 'harga' => 420000, 'stok_sekarang' => 7],
            ['nama_barang' => '[RUH018] Upper Tank Civic FD1', 'batas_minimum' => 3, 'harga' => 210000, 'stok_sekarang' => 5],
            ['nama_barang' => '[RUH019] Upper Tank Civic FD2', 'batas_minimum' => 3, 'harga' => 410000, 'stok_sekarang' => 3],
            ['nama_barang' => '[RUH020] Upper Tank Civic FB', 'batas_minimum' => 3, 'harga' => 260000, 'stok_sekarang' => 19],
            ['nama_barang' => '[RUH021] Upper Tank Civic Turbo FC', 'batas_minimum' => 3, 'harga' => 200000, 'stok_sekarang' => 20],
            ['nama_barang' => '[RUH022] Upper Tank City GD8', 'batas_minimum' => 3, 'harga' => 290000, 'stok_sekarang' => 13],
            ['nama_barang' => '[RUH023] Upper Tank City GM2', 'batas_minimum' => 3, 'harga' => 360000, 'stok_sekarang' => 10],
            ['nama_barang' => '[RUH024] Upper Tank City GM6', 'batas_minimum' => 3, 'harga' => 380000, 'stok_sekarang' => 14],
            ['nama_barang' => '[RUH025] Upper Tank Accord CP2', 'batas_minimum' => 3, 'harga' => 220000, 'stok_sekarang' => 14],
            ['nama_barang' => '[RUH026] Upper Tank Accord CR2', 'batas_minimum' => 3, 'harga' => 440000, 'stok_sekarang' => 3],
            ['nama_barang' => '[RUH027] Upper Tank Freed', 'batas_minimum' => 3, 'harga' => 440000, 'stok_sekarang' => 5],
            ['nama_barang' => '[RUH028] Upper Tank Odyssey RB1', 'batas_minimum' => 3, 'harga' => 360000, 'stok_sekarang' => 11],
            ['nama_barang' => '[RUH029] Upper Tank Odyssey RC1', 'batas_minimum' => 3, 'harga' => 390000, 'stok_sekarang' => 9],
            ['nama_barang' => '[RUH030] Upper Tank Stream 1.7', 'batas_minimum' => 3, 'harga' => 190000, 'stok_sekarang' => 11],
            ['nama_barang' => '[RUH031] Upper Tank Stream 2.0', 'batas_minimum' => 3, 'harga' => 350000, 'stok_sekarang' => 16],
            ['nama_barang' => '[RUH032] Upper Tank Elyson', 'batas_minimum' => 3, 'harga' => 310000, 'stok_sekarang' => 5],
            ['nama_barang' => '[RUD001] Upper Tank Xenia 1.0', 'batas_minimum' => 3, 'harga' => 380000, 'stok_sekarang' => 18],
            ['nama_barang' => '[RUD002] Upper Tank Xenia 1.3', 'batas_minimum' => 3, 'harga' => 310000, 'stok_sekarang' => 4],
            ['nama_barang' => '[RUD003] Upper Tank All New Xenia', 'batas_minimum' => 3, 'harga' => 200000, 'stok_sekarang' => 21],
            ['nama_barang' => '[RUD004] Upper Tank Terios Lama', 'batas_minimum' => 3, 'harga' => 320000, 'stok_sekarang' => 18],
            ['nama_barang' => '[RUD005] Upper Tank All New Terios', 'batas_minimum' => 3, 'harga' => 210000, 'stok_sekarang' => 18],
            ['nama_barang' => '[RUD006] Upper Tank Gran Max 1.3', 'batas_minimum' => 3, 'harga' => 260000, 'stok_sekarang' => 9],
            ['nama_barang' => '[RUD007] Upper Tank Gran Max 1.5', 'batas_minimum' => 3, 'harga' => 210000, 'stok_sekarang' => 19],
            ['nama_barang' => '[RUD008] Upper Tank Luxio', 'batas_minimum' => 3, 'harga' => 340000, 'stok_sekarang' => 19],
            ['nama_barang' => '[RUD009] Upper Tank Ayla 1.0', 'batas_minimum' => 3, 'harga' => 260000, 'stok_sekarang' => 14],
            ['nama_barang' => '[RUD010] Upper Tank Ayla 1.2', 'batas_minimum' => 3, 'harga' => 370000, 'stok_sekarang' => 18],
            ['nama_barang' => '[RUD011] Upper Tank Sigra 1.0', 'batas_minimum' => 3, 'harga' => 450000, 'stok_sekarang' => 4],
            ['nama_barang' => '[RUD012] Upper Tank Sigra 1.2', 'batas_minimum' => 3, 'harga' => 300000, 'stok_sekarang' => 14],
            ['nama_barang' => '[RUD013] Upper Tank Sirion Lama', 'batas_minimum' => 3, 'harga' => 310000, 'stok_sekarang' => 17],
            ['nama_barang' => '[RUD014] Upper Tank All New Sirion', 'batas_minimum' => 3, 'harga' => 320000, 'stok_sekarang' => 7],
            ['nama_barang' => '[RUD015] Upper Tank Taruna Karburator', 'batas_minimum' => 3, 'harga' => 240000, 'stok_sekarang' => 11],
            ['nama_barang' => '[RUD016] Upper Tank Taruna EFI', 'batas_minimum' => 3, 'harga' => 440000, 'stok_sekarang' => 3],
            ['nama_barang' => '[RUD017] Upper Tank Feroza', 'batas_minimum' => 3, 'harga' => 380000, 'stok_sekarang' => 19],
            ['nama_barang' => '[RUD018] Upper Tank Taft GT', 'batas_minimum' => 3, 'harga' => 150000, 'stok_sekarang' => 12],
            ['nama_barang' => '[RUD019] Upper Tank Taft Independent', 'batas_minimum' => 3, 'harga' => 250000, 'stok_sekarang' => 17],
            ['nama_barang' => '[RUD020] Upper Tank Rocky Lama', 'batas_minimum' => 3, 'harga' => 210000, 'stok_sekarang' => 8],
            ['nama_barang' => '[RUD021] Upper Tank Rocky Baru 1.0', 'batas_minimum' => 3, 'harga' => 180000, 'stok_sekarang' => 17],
            ['nama_barang' => '[RUD022] Upper Tank Rocky Baru 1.2', 'batas_minimum' => 3, 'harga' => 260000, 'stok_sekarang' => 17],
            ['nama_barang' => '[RUD023] Upper Tank Zebra 1.3', 'batas_minimum' => 3, 'harga' => 320000, 'stok_sekarang' => 21],
            ['nama_barang' => '[RUS001] Upper Tank Carry 1.0', 'batas_minimum' => 3, 'harga' => 390000, 'stok_sekarang' => 4],
            ['nama_barang' => '[RUS002] Upper Tank Carry Futura 1.5', 'batas_minimum' => 3, 'harga' => 190000, 'stok_sekarang' => 10],
            ['nama_barang' => '[RUS003] Upper Tank New Carry (Tayu)', 'batas_minimum' => 3, 'harga' => 230000, 'stok_sekarang' => 11],
            ['nama_barang' => '[RUS004] Upper Tank APV', 'batas_minimum' => 3, 'harga' => 250000, 'stok_sekarang' => 10],
            ['nama_barang' => '[RUS005] Upper Tank APV Arena', 'batas_minimum' => 3, 'harga' => 430000, 'stok_sekarang' => 21],
            ['nama_barang' => '[RUS006] Upper Tank Ertiga Lama', 'batas_minimum' => 3, 'harga' => 340000, 'stok_sekarang' => 19],
            ['nama_barang' => '[RUS007] Upper Tank All New Ertiga', 'batas_minimum' => 3, 'harga' => 370000, 'stok_sekarang' => 12],
            ['nama_barang' => '[RUS008] Upper Tank XL7', 'batas_minimum' => 3, 'harga' => 170000, 'stok_sekarang' => 4],
            ['nama_barang' => '[RUS009] Upper Tank SX4 X-Over', 'batas_minimum' => 3, 'harga' => 160000, 'stok_sekarang' => 13],
            ['nama_barang' => '[RUS010] Upper Tank SX4 S-Cross', 'batas_minimum' => 3, 'harga' => 180000, 'stok_sekarang' => 14],
            ['nama_barang' => '[RUS011] Upper Tank Grand Vitara 2.0', 'batas_minimum' => 3, 'harga' => 170000, 'stok_sekarang' => 14],
            ['nama_barang' => '[RUS012] Upper Tank Grand Vitara 2.4', 'batas_minimum' => 3, 'harga' => 200000, 'stok_sekarang' => 9],
            ['nama_barang' => '[RUS013] Upper Tank Ignis', 'batas_minimum' => 3, 'harga' => 300000, 'stok_sekarang' => 2],
            ['nama_barang' => '[RUS014] Upper Tank Baleno Lama', 'batas_minimum' => 3, 'harga' => 250000, 'stok_sekarang' => 14],
            ['nama_barang' => '[RUS015] Upper Tank Baleno Hatchback', 'batas_minimum' => 3, 'harga' => 250000, 'stok_sekarang' => 18],
            ['nama_barang' => '[RUS016] Upper Tank Aerio', 'batas_minimum' => 3, 'harga' => 380000, 'stok_sekarang' => 3],
            ['nama_barang' => '[RUS017] Upper Tank Swift ST', 'batas_minimum' => 3, 'harga' => 410000, 'stok_sekarang' => 18],
            ['nama_barang' => '[RUS018] Upper Tank Swift GT3', 'batas_minimum' => 3, 'harga' => 270000, 'stok_sekarang' => 10],
            ['nama_barang' => '[RUS019] Upper Tank Splash', 'batas_minimum' => 3, 'harga' => 260000, 'stok_sekarang' => 15],
            ['nama_barang' => '[RUS020] Upper Tank Jimny Katana', 'batas_minimum' => 3, 'harga' => 210000, 'stok_sekarang' => 14],
            ['nama_barang' => '[RUS021] Upper Tank Jimny JB74', 'batas_minimum' => 3, 'harga' => 210000, 'stok_sekarang' => 6],
            ['nama_barang' => '[RUS022] Upper Tank Karimun Kotak', 'batas_minimum' => 3, 'harga' => 340000, 'stok_sekarang' => 6],
            ['nama_barang' => '[RUS023] Upper Tank Karimun Wagon R', 'batas_minimum' => 3, 'harga' => 300000, 'stok_sekarang' => 5],
            ['nama_barang' => '[RUM001] Upper Tank Xpander', 'batas_minimum' => 3, 'harga' => 390000, 'stok_sekarang' => 5],
            ['nama_barang' => '[RUM002] Upper Tank Xpander Cross', 'batas_minimum' => 3, 'harga' => 420000, 'stok_sekarang' => 15],
            ['nama_barang' => '[RUM003] Upper Tank L300 Bensin', 'batas_minimum' => 3, 'harga' => 300000, 'stok_sekarang' => 14],
            ['nama_barang' => '[RUM004] Upper Tank L300 Diesel', 'batas_minimum' => 3, 'harga' => 400000, 'stok_sekarang' => 13],
            ['nama_barang' => '[RUM005] Upper Tank Pajero Sport Lama', 'batas_minimum' => 3, 'harga' => 240000, 'stok_sekarang' => 5],
            ['nama_barang' => '[RUM006] Upper Tank Pajero Sport Dakar', 'batas_minimum' => 3, 'harga' => 280000, 'stok_sekarang' => 15],
            ['nama_barang' => '[RUM007] Upper Tank All New Pajero Sport', 'batas_minimum' => 3, 'harga' => 190000, 'stok_sekarang' => 13],
            ['nama_barang' => '[RUM008] Upper Tank Outlander Sport', 'batas_minimum' => 3, 'harga' => 280000, 'stok_sekarang' => 7],
            ['nama_barang' => '[RUM009] Upper Tank Triton GLS', 'batas_minimum' => 3, 'harga' => 370000, 'stok_sekarang' => 6],
            ['nama_barang' => '[RUM010] Upper Tank Triton HDX', 'batas_minimum' => 3, 'harga' => 280000, 'stok_sekarang' => 19],
            ['nama_barang' => '[RUM011] Upper Tank Mirage', 'batas_minimum' => 3, 'harga' => 160000, 'stok_sekarang' => 7],
            ['nama_barang' => '[RUM012] Upper Tank Kuda Bensin 1.6', 'batas_minimum' => 3, 'harga' => 320000, 'stok_sekarang' => 5],
            ['nama_barang' => '[RUM013] Upper Tank Kuda Diesel 2.5', 'batas_minimum' => 3, 'harga' => 290000, 'stok_sekarang' => 2],
            ['nama_barang' => '[RUM014] Upper Tank Kuda Grandia 2.0', 'batas_minimum' => 3, 'harga' => 230000, 'stok_sekarang' => 3],
            ['nama_barang' => '[RUM015] Upper Tank Lancer DanGan', 'batas_minimum' => 3, 'harga' => 250000, 'stok_sekarang' => 9],
            ['nama_barang' => '[RUM016] Upper Tank Lancer Evo 3', 'batas_minimum' => 3, 'harga' => 440000, 'stok_sekarang' => 21],
            ['nama_barang' => '[RUM017] Upper Tank Lancer Evo 4', 'batas_minimum' => 3, 'harga' => 210000, 'stok_sekarang' => 17],
            ['nama_barang' => '[RUM018] Upper Tank Galant Hiu', 'batas_minimum' => 3, 'harga' => 190000, 'stok_sekarang' => 15],
            ['nama_barang' => '[RUM019] Upper Tank Colt Diesel Canter', 'batas_minimum' => 3, 'harga' => 440000, 'stok_sekarang' => 15],
            ['nama_barang' => '[RUN001] Upper Tank Grand Livina 1.5', 'batas_minimum' => 3, 'harga' => 430000, 'stok_sekarang' => 15],
            ['nama_barang' => '[RUN002] Upper Tank Grand Livina 1.8', 'batas_minimum' => 3, 'harga' => 380000, 'stok_sekarang' => 6],
            ['nama_barang' => '[RUN003] Upper Tank All New Livina', 'batas_minimum' => 3, 'harga' => 350000, 'stok_sekarang' => 20],
            ['nama_barang' => '[RUN004] Upper Tank March 1.2', 'batas_minimum' => 3, 'harga' => 370000, 'stok_sekarang' => 7],
            ['nama_barang' => '[RUN005] Upper Tank March 1.5', 'batas_minimum' => 3, 'harga' => 330000, 'stok_sekarang' => 6],
            ['nama_barang' => '[RUN006] Upper Tank Datsun Go', 'batas_minimum' => 3, 'harga' => 190000, 'stok_sekarang' => 5],
            ['nama_barang' => '[RUN007] Upper Tank Datsun Go+', 'batas_minimum' => 3, 'harga' => 200000, 'stok_sekarang' => 9],
            ['nama_barang' => '[RUN008] Upper Tank X-Trail T30', 'batas_minimum' => 3, 'harga' => 300000, 'stok_sekarang' => 15],
            ['nama_barang' => '[RUN009] Upper Tank X-Trail T31', 'batas_minimum' => 3, 'harga' => 430000, 'stok_sekarang' => 15],
            ['nama_barang' => '[RUN010] Upper Tank X-Trail T32', 'batas_minimum' => 3, 'harga' => 350000, 'stok_sekarang' => 9],
            ['nama_barang' => '[RUN011] Upper Tank Serena C24', 'batas_minimum' => 3, 'harga' => 320000, 'stok_sekarang' => 2],
            ['nama_barang' => '[RUN012] Upper Tank Serena C26', 'batas_minimum' => 3, 'harga' => 320000, 'stok_sekarang' => 10],
            ['nama_barang' => '[RUN013] Upper Tank Evalia', 'batas_minimum' => 3, 'harga' => 190000, 'stok_sekarang' => 8],
            ['nama_barang' => '[RUN014] Upper Tank Juke', 'batas_minimum' => 3, 'harga' => 220000, 'stok_sekarang' => 15],
            ['nama_barang' => '[RUN015] Upper Tank Navara D40', 'batas_minimum' => 3, 'harga' => 210000, 'stok_sekarang' => 12],
            ['nama_barang' => '[RUN016] Upper Tank Navara NP300', 'batas_minimum' => 3, 'harga' => 420000, 'stok_sekarang' => 10],
            ['nama_barang' => '[RUN017] Upper Tank Terrano', 'batas_minimum' => 3, 'harga' => 220000, 'stok_sekarang' => 15],
            ['nama_barang' => '[RUO001] Upper Tank Isuzu Panther 2.3', 'batas_minimum' => 3, 'harga' => 330000, 'stok_sekarang' => 5],
            ['nama_barang' => '[RUO002] Upper Tank Isuzu Panther 2.5', 'batas_minimum' => 3, 'harga' => 190000, 'stok_sekarang' => 10],
            ['nama_barang' => '[RUO003] Upper Tank Isuzu Elf NKR', 'batas_minimum' => 3, 'harga' => 180000, 'stok_sekarang' => 12],
            ['nama_barang' => '[RUO004] Upper Tank Isuzu MU-X', 'batas_minimum' => 3, 'harga' => 290000, 'stok_sekarang' => 14],
            ['nama_barang' => '[RUO005] Upper Tank Wuling Confero', 'batas_minimum' => 3, 'harga' => 320000, 'stok_sekarang' => 6],
            ['nama_barang' => '[RUO006] Upper Tank Wuling Cortez', 'batas_minimum' => 3, 'harga' => 440000, 'stok_sekarang' => 13],
            ['nama_barang' => '[RUO007] Upper Tank Wuling Almaz', 'batas_minimum' => 3, 'harga' => 160000, 'stok_sekarang' => 4],
            ['nama_barang' => '[RUO008] Upper Tank Wuling Formo', 'batas_minimum' => 3, 'harga' => 420000, 'stok_sekarang' => 11],
            ['nama_barang' => '[RUO009] Upper Tank Ford Fiesta 1.4', 'batas_minimum' => 3, 'harga' => 230000, 'stok_sekarang' => 10],
            ['nama_barang' => '[RUO010] Upper Tank Ford Fiesta 1.5', 'batas_minimum' => 3, 'harga' => 320000, 'stok_sekarang' => 3],
            ['nama_barang' => '[RUO011] Upper Tank Ford Everest', 'batas_minimum' => 3, 'harga' => 440000, 'stok_sekarang' => 2],
            ['nama_barang' => '[RUO012] Upper Tank Ford Ranger 2.2', 'batas_minimum' => 3, 'harga' => 320000, 'stok_sekarang' => 11],
            ['nama_barang' => '[RUO013] Upper Tank Ford Ranger 2.5', 'batas_minimum' => 3, 'harga' => 420000, 'stok_sekarang' => 8],
            ['nama_barang' => '[RUO014] Upper Tank Mazda 2 Non-Skyactiv', 'batas_minimum' => 3, 'harga' => 220000, 'stok_sekarang' => 8],
            ['nama_barang' => '[RUO015] Upper Tank Mazda 2 Skyactiv', 'batas_minimum' => 3, 'harga' => 150000, 'stok_sekarang' => 7],
            ['nama_barang' => '[RUO016] Upper Tank Mazda CX5', 'batas_minimum' => 3, 'harga' => 320000, 'stok_sekarang' => 18],
            ['nama_barang' => '[RUO017] Upper Tank Mazda Biante', 'batas_minimum' => 3, 'harga' => 310000, 'stok_sekarang' => 9],
            ['nama_barang' => '[RUO018] Upper Tank Hyundai Avega', 'batas_minimum' => 3, 'harga' => 350000, 'stok_sekarang' => 6],
            ['nama_barang' => '[RUO019] Upper Tank Hyundai Grand Avega', 'batas_minimum' => 3, 'harga' => 240000, 'stok_sekarang' => 15],
            ['nama_barang' => '[RUO020] Upper Tank Hyundai Stargazer', 'batas_minimum' => 3, 'harga' => 310000, 'stok_sekarang' => 16],
            ['nama_barang' => '[RUO021] Upper Tank Hyundai Creta', 'batas_minimum' => 3, 'harga' => 270000, 'stok_sekarang' => 13],
            ['nama_barang' => '[RUO022] Upper Tank Kia Picanto', 'batas_minimum' => 3, 'harga' => 220000, 'stok_sekarang' => 9],
            ['nama_barang' => '[RUO023] Upper Tank Kia Rio', 'batas_minimum' => 3, 'harga' => 380000, 'stok_sekarang' => 5],
            ['nama_barang' => '[RUO024] Upper Tank Kia Sonet', 'batas_minimum' => 3, 'harga' => 190000, 'stok_sekarang' => 17],
            ['nama_barang' => '[RUO025] Upper Tank Chevrolet Spin', 'batas_minimum' => 3, 'harga' => 340000, 'stok_sekarang' => 6],
            ['nama_barang' => '[RUO026] Upper Tank Chevrolet Captiva', 'batas_minimum' => 3, 'harga' => 310000, 'stok_sekarang' => 3],

            // ================= RADIATOR LOWER TANK =================
            ['nama_barang' => '[RLT001] Lower Tank Avanza Lama', 'batas_minimum' => 3, 'harga' => 400000, 'stok_sekarang' => 14],
            ['nama_barang' => '[RLT002] Lower Tank Avanza VVT-i', 'batas_minimum' => 3, 'harga' => 160000, 'stok_sekarang' => 7],
            ['nama_barang' => '[RLT003] Lower Tank Avanza Dual VVT-i', 'batas_minimum' => 3, 'harga' => 310000, 'stok_sekarang' => 4],
            ['nama_barang' => '[RLT004] Lower Tank All New Avanza', 'batas_minimum' => 3, 'harga' => 440000, 'stok_sekarang' => 5],
            ['nama_barang' => '[RLT005] Lower Tank Innova Bensin 2.0', 'batas_minimum' => 3, 'harga' => 390000, 'stok_sekarang' => 8],
            ['nama_barang' => '[RLT006] Lower Tank Innova Diesel 2.5', 'batas_minimum' => 3, 'harga' => 430000, 'stok_sekarang' => 2],
            ['nama_barang' => '[RLT007] Lower Tank Innova Reborn Bensin', 'batas_minimum' => 3, 'harga' => 380000, 'stok_sekarang' => 7],
            ['nama_barang' => '[RLT008] Lower Tank Innova Reborn Diesel', 'batas_minimum' => 3, 'harga' => 350000, 'stok_sekarang' => 20],
            ['nama_barang' => '[RLT009] Lower Tank Innova Zenix', 'batas_minimum' => 3, 'harga' => 270000, 'stok_sekarang' => 20],
            ['nama_barang' => '[RLT010] Lower Tank Fortuner Non-VNT', 'batas_minimum' => 3, 'harga' => 310000, 'stok_sekarang' => 2],
            ['nama_barang' => '[RLT011] Lower Tank Fortuner VNT', 'batas_minimum' => 3, 'harga' => 210000, 'stok_sekarang' => 4],
            ['nama_barang' => '[RLT012] Lower Tank Fortuner VRZ', 'batas_minimum' => 3, 'harga' => 390000, 'stok_sekarang' => 19],
            ['nama_barang' => '[RLT013] Lower Tank Hilux Single Cabin', 'batas_minimum' => 3, 'harga' => 170000, 'stok_sekarang' => 20],
            ['nama_barang' => '[RLT014] Lower Tank Hilux Double Cabin', 'batas_minimum' => 3, 'harga' => 380000, 'stok_sekarang' => 20],
            ['nama_barang' => '[RLT015] Lower Tank Agya 1.0', 'batas_minimum' => 3, 'harga' => 450000, 'stok_sekarang' => 15],
            ['nama_barang' => '[RLT016] Lower Tank Agya 1.2', 'batas_minimum' => 3, 'harga' => 350000, 'stok_sekarang' => 3],
            ['nama_barang' => '[RLT017] Lower Tank Calya 1.2', 'batas_minimum' => 3, 'harga' => 270000, 'stok_sekarang' => 20],
            ['nama_barang' => '[RLT018] Lower Tank Rush Lama', 'batas_minimum' => 3, 'harga' => 390000, 'stok_sekarang' => 21],
            ['nama_barang' => '[RLT019] Lower Tank All New Rush', 'batas_minimum' => 3, 'harga' => 380000, 'stok_sekarang' => 14],
            ['nama_barang' => '[RLT020] Lower Tank Raize 1.0 Turbo', 'batas_minimum' => 3, 'harga' => 360000, 'stok_sekarang' => 16],
            ['nama_barang' => '[RLT021] Lower Tank Raize 1.2', 'batas_minimum' => 3, 'harga' => 330000, 'stok_sekarang' => 15],
            ['nama_barang' => '[RLT022] Lower Tank Yaris Bakpao', 'batas_minimum' => 3, 'harga' => 220000, 'stok_sekarang' => 16],
            ['nama_barang' => '[RLT023] Lower Tank Yaris Lele', 'batas_minimum' => 3, 'harga' => 390000, 'stok_sekarang' => 2],
            ['nama_barang' => '[RLT024] Lower Tank Yaris Joker', 'batas_minimum' => 3, 'harga' => 340000, 'stok_sekarang' => 11],
            ['nama_barang' => '[RLT025] Lower Tank Vios Gen 1', 'batas_minimum' => 3, 'harga' => 390000, 'stok_sekarang' => 15],
            ['nama_barang' => '[RLT026] Lower Tank Vios Gen 2', 'batas_minimum' => 3, 'harga' => 180000, 'stok_sekarang' => 5],
            ['nama_barang' => '[RLT027] Lower Tank Vios Gen 3', 'batas_minimum' => 3, 'harga' => 330000, 'stok_sekarang' => 12],
            ['nama_barang' => '[RLT028] Lower Tank Camry 2.4', 'batas_minimum' => 3, 'harga' => 260000, 'stok_sekarang' => 5],
            ['nama_barang' => '[RLT029] Lower Tank Camry 2.5', 'batas_minimum' => 3, 'harga' => 190000, 'stok_sekarang' => 7],
            ['nama_barang' => '[RLT030] Lower Tank Altis Gen 1', 'batas_minimum' => 3, 'harga' => 390000, 'stok_sekarang' => 13],
            ['nama_barang' => '[RLT031] Lower Tank Altis Gen 2', 'batas_minimum' => 3, 'harga' => 250000, 'stok_sekarang' => 18],
            ['nama_barang' => '[RLT032] Lower Tank Alphard 2.4', 'batas_minimum' => 3, 'harga' => 450000, 'stok_sekarang' => 10],
            ['nama_barang' => '[RLT033] Lower Tank Alphard 2.5', 'batas_minimum' => 3, 'harga' => 170000, 'stok_sekarang' => 9],
            ['nama_barang' => '[RLT034] Lower Tank Vellfire', 'batas_minimum' => 3, 'harga' => 420000, 'stok_sekarang' => 9],
            ['nama_barang' => '[RLT035] Lower Tank Sienta', 'batas_minimum' => 3, 'harga' => 270000, 'stok_sekarang' => 11],
            ['nama_barang' => '[RLT036] Lower Tank Voxy', 'batas_minimum' => 3, 'harga' => 310000, 'stok_sekarang' => 19],
            ['nama_barang' => '[RLT037] Lower Tank Nav1', 'batas_minimum' => 3, 'harga' => 410000, 'stok_sekarang' => 21],
            ['nama_barang' => '[RLT038] Lower Tank Harrier 2.4', 'batas_minimum' => 3, 'harga' => 450000, 'stok_sekarang' => 5],
            ['nama_barang' => '[RLT039] Lower Tank Kijang Super', 'batas_minimum' => 3, 'harga' => 280000, 'stok_sekarang' => 14],
            ['nama_barang' => '[RLT040] Lower Tank Kijang Grand Extra', 'batas_minimum' => 3, 'harga' => 230000, 'stok_sekarang' => 17],
            ['nama_barang' => '[RLT041] Lower Tank Kijang Kapsul 1.8', 'batas_minimum' => 3, 'harga' => 450000, 'stok_sekarang' => 9],
            ['nama_barang' => '[RLT042] Lower Tank Kijang Kapsul 2.0', 'batas_minimum' => 3, 'harga' => 340000, 'stok_sekarang' => 5],
            ['nama_barang' => '[RLT043] Lower Tank Kijang Kapsul Diesel', 'batas_minimum' => 3, 'harga' => 280000, 'stok_sekarang' => 4],
            ['nama_barang' => '[RLT044] Lower Tank Hiace Commuter', 'batas_minimum' => 3, 'harga' => 310000, 'stok_sekarang' => 4],
            ['nama_barang' => '[RLT045] Lower Tank Hiace Premio', 'batas_minimum' => 3, 'harga' => 200000, 'stok_sekarang' => 18],
            ['nama_barang' => '[RLT046] Lower Tank Land Cruiser VX80', 'batas_minimum' => 3, 'harga' => 330000, 'stok_sekarang' => 19],
            ['nama_barang' => '[RLH001] Lower Tank Jazz GD3', 'batas_minimum' => 3, 'harga' => 410000, 'stok_sekarang' => 16],
            ['nama_barang' => '[RLH002] Lower Tank Jazz GE8', 'batas_minimum' => 3, 'harga' => 280000, 'stok_sekarang' => 21],
            ['nama_barang' => '[RLH003] Lower Tank Jazz GK5', 'batas_minimum' => 3, 'harga' => 260000, 'stok_sekarang' => 15],
            ['nama_barang' => '[RLH004] Lower Tank Brio 1.2', 'batas_minimum' => 3, 'harga' => 420000, 'stok_sekarang' => 3],
            ['nama_barang' => '[RLH005] Lower Tank Mobilio', 'batas_minimum' => 3, 'harga' => 350000, 'stok_sekarang' => 3],
            ['nama_barang' => '[RLH006] Lower Tank BRV Lama', 'batas_minimum' => 3, 'harga' => 200000, 'stok_sekarang' => 12],
            ['nama_barang' => '[RLH007] Lower Tank All New BRV', 'batas_minimum' => 3, 'harga' => 240000, 'stok_sekarang' => 15],
            ['nama_barang' => '[RLH008] Lower Tank HRV 1.5', 'batas_minimum' => 3, 'harga' => 210000, 'stok_sekarang' => 3],
            ['nama_barang' => '[RLH009] Lower Tank HRV 1.8', 'batas_minimum' => 3, 'harga' => 160000, 'stok_sekarang' => 10],
            ['nama_barang' => '[RLH010] Lower Tank HRV Turbo', 'batas_minimum' => 3, 'harga' => 420000, 'stok_sekarang' => 18],
            ['nama_barang' => '[RLH011] Lower Tank CRV Gen 1', 'batas_minimum' => 3, 'harga' => 240000, 'stok_sekarang' => 4],
            ['nama_barang' => '[RLH012] Lower Tank CRV Gen 2', 'batas_minimum' => 3, 'harga' => 150000, 'stok_sekarang' => 13],
            ['nama_barang' => '[RLH013] Lower Tank CRV Gen 3 2.0', 'batas_minimum' => 3, 'harga' => 300000, 'stok_sekarang' => 18],
            ['nama_barang' => '[RLH014] Lower Tank CRV Gen 3 2.4', 'batas_minimum' => 3, 'harga' => 230000, 'stok_sekarang' => 18],
            ['nama_barang' => '[RLH015] Lower Tank CRV Gen 4', 'batas_minimum' => 3, 'harga' => 400000, 'stok_sekarang' => 9],
            ['nama_barang' => '[RLH016] Lower Tank CRV Gen 5 Turbo', 'batas_minimum' => 3, 'harga' => 410000, 'stok_sekarang' => 21],
            ['nama_barang' => '[RLH017] Lower Tank Civic Ferio', 'batas_minimum' => 3, 'harga' => 270000, 'stok_sekarang' => 21],
            ['nama_barang' => '[RLH018] Lower Tank Civic FD1', 'batas_minimum' => 3, 'harga' => 390000, 'stok_sekarang' => 15],
            ['nama_barang' => '[RLH019] Lower Tank Civic FD2', 'batas_minimum' => 3, 'harga' => 220000, 'stok_sekarang' => 18],
            ['nama_barang' => '[RLH020] Lower Tank Civic FB', 'batas_minimum' => 3, 'harga' => 200000, 'stok_sekarang' => 21],
            ['nama_barang' => '[RLH021] Lower Tank Civic Turbo FC', 'batas_minimum' => 3, 'harga' => 450000, 'stok_sekarang' => 9],
            ['nama_barang' => '[RLH022] Lower Tank City GD8', 'batas_minimum' => 3, 'harga' => 350000, 'stok_sekarang' => 18],
            ['nama_barang' => '[RLH023] Lower Tank City GM2', 'batas_minimum' => 3, 'harga' => 330000, 'stok_sekarang' => 6],
            ['nama_barang' => '[RLH024] Lower Tank City GM6', 'batas_minimum' => 3, 'harga' => 200000, 'stok_sekarang' => 15],
            ['nama_barang' => '[RLH025] Lower Tank Accord CP2', 'batas_minimum' => 3, 'harga' => 390000, 'stok_sekarang' => 12],
            ['nama_barang' => '[RLH026] Lower Tank Accord CR2', 'batas_minimum' => 3, 'harga' => 420000, 'stok_sekarang' => 12],
            ['nama_barang' => '[RLH027] Lower Tank Freed', 'batas_minimum' => 3, 'harga' => 320000, 'stok_sekarang' => 4],
            ['nama_barang' => '[RLH028] Lower Tank Odyssey RB1', 'batas_minimum' => 3, 'harga' => 380000, 'stok_sekarang' => 13],
            ['nama_barang' => '[RLH029] Lower Tank Odyssey RC1', 'batas_minimum' => 3, 'harga' => 280000, 'stok_sekarang' => 3],
            ['nama_barang' => '[RLH030] Lower Tank Stream 1.7', 'batas_minimum' => 3, 'harga' => 400000, 'stok_sekarang' => 4],
            ['nama_barang' => '[RLH031] Lower Tank Stream 2.0', 'batas_minimum' => 3, 'harga' => 410000, 'stok_sekarang' => 17],
            ['nama_barang' => '[RLH032] Lower Tank Elyson', 'batas_minimum' => 3, 'harga' => 390000, 'stok_sekarang' => 19],
            ['nama_barang' => '[RLD001] Lower Tank Xenia 1.0', 'batas_minimum' => 3, 'harga' => 450000, 'stok_sekarang' => 19],
            ['nama_barang' => '[RLD002] Lower Tank Xenia 1.3', 'batas_minimum' => 3, 'harga' => 370000, 'stok_sekarang' => 11],
            ['nama_barang' => '[RLD003] Lower Tank All New Xenia', 'batas_minimum' => 3, 'harga' => 200000, 'stok_sekarang' => 11],
            ['nama_barang' => '[RLD004] Lower Tank Terios Lama', 'batas_minimum' => 3, 'harga' => 250000, 'stok_sekarang' => 12],
            ['nama_barang' => '[RLD005] Lower Tank All New Terios', 'batas_minimum' => 3, 'harga' => 390000, 'stok_sekarang' => 12],
            ['nama_barang' => '[RLD006] Lower Tank Gran Max 1.3', 'batas_minimum' => 3, 'harga' => 440000, 'stok_sekarang' => 17],
            ['nama_barang' => '[RLD007] Lower Tank Gran Max 1.5', 'batas_minimum' => 3, 'harga' => 330000, 'stok_sekarang' => 10],
            ['nama_barang' => '[RLD008] Lower Tank Luxio', 'batas_minimum' => 3, 'harga' => 400000, 'stok_sekarang' => 5],
            ['nama_barang' => '[RLD009] Lower Tank Ayla 1.0', 'batas_minimum' => 3, 'harga' => 290000, 'stok_sekarang' => 6],
            ['nama_barang' => '[RLD010] Lower Tank Ayla 1.2', 'batas_minimum' => 3, 'harga' => 290000, 'stok_sekarang' => 14],
            ['nama_barang' => '[RLD011] Lower Tank Sigra 1.0', 'batas_minimum' => 3, 'harga' => 410000, 'stok_sekarang' => 16],
            ['nama_barang' => '[RLD012] Lower Tank Sigra 1.2', 'batas_minimum' => 3, 'harga' => 260000, 'stok_sekarang' => 6],
            ['nama_barang' => '[RLD013] Lower Tank Sirion Lama', 'batas_minimum' => 3, 'harga' => 430000, 'stok_sekarang' => 9],
            ['nama_barang' => '[RLD014] Lower Tank All New Sirion', 'batas_minimum' => 3, 'harga' => 390000, 'stok_sekarang' => 13],
            ['nama_barang' => '[RLD015] Lower Tank Taruna Karburator', 'batas_minimum' => 3, 'harga' => 420000, 'stok_sekarang' => 9],
            ['nama_barang' => '[RLD016] Lower Tank Taruna EFI', 'batas_minimum' => 3, 'harga' => 350000, 'stok_sekarang' => 21],
            ['nama_barang' => '[RLD017] Lower Tank Feroza', 'batas_minimum' => 3, 'harga' => 390000, 'stok_sekarang' => 5],
            ['nama_barang' => '[RLD018] Lower Tank Taft GT', 'batas_minimum' => 3, 'harga' => 270000, 'stok_sekarang' => 5],
            ['nama_barang' => '[RLD019] Lower Tank Taft Independent', 'batas_minimum' => 3, 'harga' => 450000, 'stok_sekarang' => 6],
            ['nama_barang' => '[RLD020] Lower Tank Rocky Lama', 'batas_minimum' => 3, 'harga' => 310000, 'stok_sekarang' => 12],
            ['nama_barang' => '[RLD021] Lower Tank Rocky Baru 1.0', 'batas_minimum' => 3, 'harga' => 170000, 'stok_sekarang' => 16],
            ['nama_barang' => '[RLD022] Lower Tank Rocky Baru 1.2', 'batas_minimum' => 3, 'harga' => 390000, 'stok_sekarang' => 9],
            ['nama_barang' => '[RLD023] Lower Tank Zebra 1.3', 'batas_minimum' => 3, 'harga' => 230000, 'stok_sekarang' => 17],
            ['nama_barang' => '[RLS001] Lower Tank Carry 1.0', 'batas_minimum' => 3, 'harga' => 240000, 'stok_sekarang' => 3],
            ['nama_barang' => '[RLS002] Lower Tank Carry Futura 1.5', 'batas_minimum' => 3, 'harga' => 280000, 'stok_sekarang' => 10],
            ['nama_barang' => '[RLS003] Lower Tank New Carry (Tayu)', 'batas_minimum' => 3, 'harga' => 410000, 'stok_sekarang' => 17],
            ['nama_barang' => '[RLS004] Lower Tank APV', 'batas_minimum' => 3, 'harga' => 410000, 'stok_sekarang' => 10],
            ['nama_barang' => '[RLS005] Lower Tank APV Arena', 'batas_minimum' => 3, 'harga' => 160000, 'stok_sekarang' => 6],
            ['nama_barang' => '[RLS006] Lower Tank Ertiga Lama', 'batas_minimum' => 3, 'harga' => 310000, 'stok_sekarang' => 9],
            ['nama_barang' => '[RLS007] Lower Tank All New Ertiga', 'batas_minimum' => 3, 'harga' => 260000, 'stok_sekarang' => 12],
            ['nama_barang' => '[RLS008] Lower Tank XL7', 'batas_minimum' => 3, 'harga' => 350000, 'stok_sekarang' => 17],
            ['nama_barang' => '[RLS009] Lower Tank SX4 X-Over', 'batas_minimum' => 3, 'harga' => 300000, 'stok_sekarang' => 4],
            ['nama_barang' => '[RLS010] Lower Tank SX4 S-Cross', 'batas_minimum' => 3, 'harga' => 380000, 'stok_sekarang' => 14],
            ['nama_barang' => '[RLS011] Lower Tank Grand Vitara 2.0', 'batas_minimum' => 3, 'harga' => 200000, 'stok_sekarang' => 21],
            ['nama_barang' => '[RLS012] Lower Tank Grand Vitara 2.4', 'batas_minimum' => 3, 'harga' => 350000, 'stok_sekarang' => 18],
            ['nama_barang' => '[RLS013] Lower Tank Ignis', 'batas_minimum' => 3, 'harga' => 360000, 'stok_sekarang' => 20],
            ['nama_barang' => '[RLS014] Lower Tank Baleno Lama', 'batas_minimum' => 3, 'harga' => 440000, 'stok_sekarang' => 2],
            ['nama_barang' => '[RLS015] Lower Tank Baleno Hatchback', 'batas_minimum' => 3, 'harga' => 380000, 'stok_sekarang' => 13],
            ['nama_barang' => '[RLS016] Lower Tank Aerio', 'batas_minimum' => 3, 'harga' => 230000, 'stok_sekarang' => 5],
            ['nama_barang' => '[RLS017] Lower Tank Swift ST', 'batas_minimum' => 3, 'harga' => 380000, 'stok_sekarang' => 2],
            ['nama_barang' => '[RLS018] Lower Tank Swift GT3', 'batas_minimum' => 3, 'harga' => 200000, 'stok_sekarang' => 17],
            ['nama_barang' => '[RLS019] Lower Tank Splash', 'batas_minimum' => 3, 'harga' => 190000, 'stok_sekarang' => 13],
            ['nama_barang' => '[RLS020] Lower Tank Jimny Katana', 'batas_minimum' => 3, 'harga' => 400000, 'stok_sekarang' => 15],
            ['nama_barang' => '[RLS021] Lower Tank Jimny JB74', 'batas_minimum' => 3, 'harga' => 410000, 'stok_sekarang' => 20],
            ['nama_barang' => '[RLS022] Lower Tank Karimun Kotak', 'batas_minimum' => 3, 'harga' => 450000, 'stok_sekarang' => 2],
            ['nama_barang' => '[RLS023] Lower Tank Karimun Wagon R', 'batas_minimum' => 3, 'harga' => 350000, 'stok_sekarang' => 18],
            ['nama_barang' => '[RLM001] Lower Tank Xpander', 'batas_minimum' => 3, 'harga' => 190000, 'stok_sekarang' => 11],
            ['nama_barang' => '[RLM002] Lower Tank Xpander Cross', 'batas_minimum' => 3, 'harga' => 180000, 'stok_sekarang' => 11],
            ['nama_barang' => '[RLM003] Lower Tank L300 Bensin', 'batas_minimum' => 3, 'harga' => 330000, 'stok_sekarang' => 8],
            ['nama_barang' => '[RLM004] Lower Tank L300 Diesel', 'batas_minimum' => 3, 'harga' => 430000, 'stok_sekarang' => 15],
            ['nama_barang' => '[RLM005] Lower Tank Pajero Sport Lama', 'batas_minimum' => 3, 'harga' => 360000, 'stok_sekarang' => 20],
            ['nama_barang' => '[RLM006] Lower Tank Pajero Sport Dakar', 'batas_minimum' => 3, 'harga' => 450000, 'stok_sekarang' => 3],
            ['nama_barang' => '[RLM007] Lower Tank All New Pajero Sport', 'batas_minimum' => 3, 'harga' => 160000, 'stok_sekarang' => 8],
            ['nama_barang' => '[RLM008] Lower Tank Outlander Sport', 'batas_minimum' => 3, 'harga' => 170000, 'stok_sekarang' => 17],
            ['nama_barang' => '[RLM009] Lower Tank Triton GLS', 'batas_minimum' => 3, 'harga' => 440000, 'stok_sekarang' => 3],
            ['nama_barang' => '[RLM010] Lower Tank Triton HDX', 'batas_minimum' => 3, 'harga' => 440000, 'stok_sekarang' => 4],
            ['nama_barang' => '[RLM011] Lower Tank Mirage', 'batas_minimum' => 3, 'harga' => 320000, 'stok_sekarang' => 7],
            ['nama_barang' => '[RLM012] Lower Tank Kuda Bensin 1.6', 'batas_minimum' => 3, 'harga' => 390000, 'stok_sekarang' => 10],
            ['nama_barang' => '[RLM013] Lower Tank Kuda Diesel 2.5', 'batas_minimum' => 3, 'harga' => 270000, 'stok_sekarang' => 4],
            ['nama_barang' => '[RLM014] Lower Tank Kuda Grandia 2.0', 'batas_minimum' => 3, 'harga' => 300000, 'stok_sekarang' => 17],
            ['nama_barang' => '[RLM015] Lower Tank Lancer DanGan', 'batas_minimum' => 3, 'harga' => 380000, 'stok_sekarang' => 21],
            ['nama_barang' => '[RLM016] Lower Tank Lancer Evo 3', 'batas_minimum' => 3, 'harga' => 430000, 'stok_sekarang' => 8],
            ['nama_barang' => '[RLM017] Lower Tank Lancer Evo 4', 'batas_minimum' => 3, 'harga' => 180000, 'stok_sekarang' => 21],
            ['nama_barang' => '[RLM018] Lower Tank Galant Hiu', 'batas_minimum' => 3, 'harga' => 390000, 'stok_sekarang' => 18],
            ['nama_barang' => '[RLM019] Lower Tank Colt Diesel Canter', 'batas_minimum' => 3, 'harga' => 380000, 'stok_sekarang' => 14],
            ['nama_barang' => '[RLN001] Lower Tank Grand Livina 1.5', 'batas_minimum' => 3, 'harga' => 370000, 'stok_sekarang' => 13],
            ['nama_barang' => '[RLN002] Lower Tank Grand Livina 1.8', 'batas_minimum' => 3, 'harga' => 280000, 'stok_sekarang' => 13],
            ['nama_barang' => '[RLN003] Lower Tank All New Livina', 'batas_minimum' => 3, 'harga' => 190000, 'stok_sekarang' => 20],
            ['nama_barang' => '[RLN004] Lower Tank March 1.2', 'batas_minimum' => 3, 'harga' => 440000, 'stok_sekarang' => 7],
            ['nama_barang' => '[RLN005] Lower Tank March 1.5', 'batas_minimum' => 3, 'harga' => 340000, 'stok_sekarang' => 17],
            ['nama_barang' => '[RLN006] Lower Tank Datsun Go', 'batas_minimum' => 3, 'harga' => 380000, 'stok_sekarang' => 6],
            ['nama_barang' => '[RLN007] Lower Tank Datsun Go+', 'batas_minimum' => 3, 'harga' => 200000, 'stok_sekarang' => 11],
            ['nama_barang' => '[RLN008] Lower Tank X-Trail T30', 'batas_minimum' => 3, 'harga' => 430000, 'stok_sekarang' => 12],
            ['nama_barang' => '[RLN009] Lower Tank X-Trail T31', 'batas_minimum' => 3, 'harga' => 270000, 'stok_sekarang' => 4],
            ['nama_barang' => '[RLN010] Lower Tank X-Trail T32', 'batas_minimum' => 3, 'harga' => 320000, 'stok_sekarang' => 12],
            ['nama_barang' => '[RLN011] Lower Tank Serena C24', 'batas_minimum' => 3, 'harga' => 150000, 'stok_sekarang' => 3],
            ['nama_barang' => '[RLN012] Lower Tank Serena C26', 'batas_minimum' => 3, 'harga' => 150000, 'stok_sekarang' => 19],
            ['nama_barang' => '[RLN013] Lower Tank Evalia', 'batas_minimum' => 3, 'harga' => 230000, 'stok_sekarang' => 6],
            ['nama_barang' => '[RLN014] Lower Tank Juke', 'batas_minimum' => 3, 'harga' => 400000, 'stok_sekarang' => 19],
            ['nama_barang' => '[RLN015] Lower Tank Navara D40', 'batas_minimum' => 3, 'harga' => 300000, 'stok_sekarang' => 8],
            ['nama_barang' => '[RLN016] Lower Tank Navara NP300', 'batas_minimum' => 3, 'harga' => 300000, 'stok_sekarang' => 4],
            ['nama_barang' => '[RLN017] Lower Tank Terrano', 'batas_minimum' => 3, 'harga' => 390000, 'stok_sekarang' => 5],
            ['nama_barang' => '[RLO001] Lower Tank Isuzu Panther 2.3', 'batas_minimum' => 3, 'harga' => 210000, 'stok_sekarang' => 9],
            ['nama_barang' => '[RLO002] Lower Tank Isuzu Panther 2.5', 'batas_minimum' => 3, 'harga' => 290000, 'stok_sekarang' => 7],
            ['nama_barang' => '[RLO003] Lower Tank Isuzu Elf NKR', 'batas_minimum' => 3, 'harga' => 450000, 'stok_sekarang' => 10],
            ['nama_barang' => '[RLO004] Lower Tank Isuzu MU-X', 'batas_minimum' => 3, 'harga' => 270000, 'stok_sekarang' => 4],
            ['nama_barang' => '[RLO005] Lower Tank Wuling Confero', 'batas_minimum' => 3, 'harga' => 370000, 'stok_sekarang' => 12],
            ['nama_barang' => '[RLO006] Lower Tank Wuling Cortez', 'batas_minimum' => 3, 'harga' => 350000, 'stok_sekarang' => 3],
            ['nama_barang' => '[RLO007] Lower Tank Wuling Almaz', 'batas_minimum' => 3, 'harga' => 280000, 'stok_sekarang' => 9],
            ['nama_barang' => '[RLO008] Lower Tank Wuling Formo', 'batas_minimum' => 3, 'harga' => 260000, 'stok_sekarang' => 5],
            ['nama_barang' => '[RLO009] Lower Tank Ford Fiesta 1.4', 'batas_minimum' => 3, 'harga' => 380000, 'stok_sekarang' => 6],
            ['nama_barang' => '[RLO010] Lower Tank Ford Fiesta 1.5', 'batas_minimum' => 3, 'harga' => 270000, 'stok_sekarang' => 20],
            ['nama_barang' => '[RLO011] Lower Tank Ford Everest', 'batas_minimum' => 3, 'harga' => 220000, 'stok_sekarang' => 12],
            ['nama_barang' => '[RLO012] Lower Tank Ford Ranger 2.2', 'batas_minimum' => 3, 'harga' => 330000, 'stok_sekarang' => 12],
            ['nama_barang' => '[RLO013] Lower Tank Ford Ranger 2.5', 'batas_minimum' => 3, 'harga' => 170000, 'stok_sekarang' => 12],
            ['nama_barang' => '[RLO014] Lower Tank Mazda 2 Non-Skyactiv', 'batas_minimum' => 3, 'harga' => 350000, 'stok_sekarang' => 16],
            ['nama_barang' => '[RLO015] Lower Tank Mazda 2 Skyactiv', 'batas_minimum' => 3, 'harga' => 240000, 'stok_sekarang' => 8],
            ['nama_barang' => '[RLO016] Lower Tank Mazda CX5', 'batas_minimum' => 3, 'harga' => 400000, 'stok_sekarang' => 20],
            ['nama_barang' => '[RLO017] Lower Tank Mazda Biante', 'batas_minimum' => 3, 'harga' => 440000, 'stok_sekarang' => 2],
            ['nama_barang' => '[RLO018] Lower Tank Hyundai Avega', 'batas_minimum' => 3, 'harga' => 190000, 'stok_sekarang' => 4],
            ['nama_barang' => '[RLO019] Lower Tank Hyundai Grand Avega', 'batas_minimum' => 3, 'harga' => 430000, 'stok_sekarang' => 21],
            ['nama_barang' => '[RLO020] Lower Tank Hyundai Stargazer', 'batas_minimum' => 3, 'harga' => 260000, 'stok_sekarang' => 11],
            ['nama_barang' => '[RLO021] Lower Tank Hyundai Creta', 'batas_minimum' => 3, 'harga' => 380000, 'stok_sekarang' => 9],
            ['nama_barang' => '[RLO022] Lower Tank Kia Picanto', 'batas_minimum' => 3, 'harga' => 420000, 'stok_sekarang' => 9],
            ['nama_barang' => '[RLO023] Lower Tank Kia Rio', 'batas_minimum' => 3, 'harga' => 260000, 'stok_sekarang' => 6],
            ['nama_barang' => '[RLO024] Lower Tank Kia Sonet', 'batas_minimum' => 3, 'harga' => 390000, 'stok_sekarang' => 7],
            ['nama_barang' => '[RLO025] Lower Tank Chevrolet Spin', 'batas_minimum' => 3, 'harga' => 220000, 'stok_sekarang' => 3],
            ['nama_barang' => '[RLO026] Lower Tank Chevrolet Captiva', 'batas_minimum' => 3, 'harga' => 230000, 'stok_sekarang' => 5],

            // ================= CAIRAN COOLANT =================
            ['nama_barang' => '[CLU001] Coolant Prestone Merah 4L', 'batas_minimum' => 10, 'harga' => 125000, 'stok_sekarang' => 54],
            ['nama_barang' => '[CLU002] Coolant Prestone Hijau 4L', 'batas_minimum' => 10, 'harga' => 125000, 'stok_sekarang' => 13],
            ['nama_barang' => '[CLU003] Coolant Top1 Merah 1L', 'batas_minimum' => 10, 'harga' => 35000, 'stok_sekarang' => 36],
            ['nama_barang' => '[CLU004] Coolant Top1 Hijau 1L', 'batas_minimum' => 10, 'harga' => 35000, 'stok_sekarang' => 55],
            ['nama_barang' => '[CLU005] Coolant Megacools Hijau 1L', 'batas_minimum' => 10, 'harga' => 25000, 'stok_sekarang' => 41],
            ['nama_barang' => '[CLU006] Coolant Megacools Merah 1L', 'batas_minimum' => 10, 'harga' => 25000, 'stok_sekarang' => 28],
            ['nama_barang' => '[CLU007] Air Radiator Aquadest 5L', 'batas_minimum' => 10, 'harga' => 20000, 'stok_sekarang' => 88],
            ['nama_barang' => '[CLU008] Coolant Wurth Biru 5L', 'batas_minimum' => 10, 'harga' => 200000, 'stok_sekarang' => 16],
            ['nama_barang' => '[CLU009] Coolant Jumbo Hijau 4L', 'batas_minimum' => 10, 'harga' => 80000, 'stok_sekarang' => 20],
            ['nama_barang' => '[CLT001] Toyota Motor Oil (TMO) Coolant Merah 4L', 'batas_minimum' => 10, 'harga' => 160000, 'stok_sekarang' => 43],
            ['nama_barang' => '[CLT002] Toyota Motor Oil (TMO) Coolant Merah 1L', 'batas_minimum' => 10, 'harga' => 45000, 'stok_sekarang' => 23],
            ['nama_barang' => '[CLH001] Honda Radiator Coolant Type 2 (Biru) 4L', 'batas_minimum' => 10, 'harga' => 175000, 'stok_sekarang' => 26],
            ['nama_barang' => '[CLH002] Honda Radiator Coolant Type 1 (Hijau) 4L', 'batas_minimum' => 10, 'harga' => 165000, 'stok_sekarang' => 72],
            ['nama_barang' => '[CLH003] Honda Radiator Coolant (Biru) 1L', 'batas_minimum' => 10, 'harga' => 50000, 'stok_sekarang' => 30],
            ['nama_barang' => '[CLD001] Daihatsu Genuine Coolant Merah 4L', 'batas_minimum' => 10, 'harga' => 155000, 'stok_sekarang' => 78],
            ['nama_barang' => '[CLS001] Suzuki Ecstar Coolant Biru 4L', 'batas_minimum' => 10, 'harga' => 150000, 'stok_sekarang' => 72],
            ['nama_barang' => '[CLS002] Suzuki Ecstar Coolant Biru 1L', 'batas_minimum' => 10, 'harga' => 40000, 'stok_sekarang' => 13],
            ['nama_barang' => '[CLM001] Mitsubishi Motors Genuine Coolant Hijau 4L', 'batas_minimum' => 10, 'harga' => 180000, 'stok_sekarang' => 55],
            ['nama_barang' => '[CLM002] Mitsubishi Motors Genuine Coolant Hijau 1L', 'batas_minimum' => 10, 'harga' => 55000, 'stok_sekarang' => 40],
            ['nama_barang' => '[CLN001] Nissan Genuine Coolant Biru 4L', 'batas_minimum' => 10, 'harga' => 170000, 'stok_sekarang' => 69],

            // ================= JASA SERVIS =================
            ['nama_barang' => '[JSU001] Isi Freon AC (Jasa + Freon R134a Full)', 'batas_minimum' => 0, 'harga' => 200000, 'stok_sekarang' => 999],
            ['nama_barang' => '[JSU002] Tambah Freon AC (Setengah)', 'batas_minimum' => 0, 'harga' => 100000, 'stok_sekarang' => 999],
            ['nama_barang' => '[JSU003] Jasa Korok Radiator Mobil Kecil', 'batas_minimum' => 0, 'harga' => 150000, 'stok_sekarang' => 999],
            ['nama_barang' => '[JSU004] Jasa Korok Radiator Mobil Besar/Truk', 'batas_minimum' => 0, 'harga' => 250000, 'stok_sekarang' => 999],
            ['nama_barang' => '[JSU008] Jasa Ganti Upper/Lower Tank (Termasuk Lem)', 'batas_minimum' => 0, 'harga' => 100000, 'stok_sekarang' => 999],
        ];

        foreach ($sparepart as $sp) {
            // Ekstrak kode barang dari nama barang (contoh: "[RUT001] Upper Tank" -> kode: "RUT001", nama: "Upper Tank")
            if (preg_match('/\[(.*?)\]\s*(.*)/', $sp['nama_barang'], $matches)) {
                $sp['kode_barang'] = $matches[1];
                $sp['nama_barang'] = $matches[2];
            } else {
                $sp['kode_barang'] = 'SP-' . rand(1000, 9999);
            }
            Sparepart::firstOrCreate(['kode_barang' => $sp['kode_barang']], $sp);
        }
    }
}
